composer.json.dist

Alias branch also removed in `composer.json` file.
Don't merge right now there might be an issue.

Update portfolio, website and dropzone version to compatible version with core 4.0

---

.gitignore
README.md
composer-v6.json
make.js
package.json

[PLEASE create a v5 branch before merging this PR]
- basic setup, including only css/less stuff for now
- readme re-written with updated instructions
- needs a 6.7.0 tag on core bundle (which in turn needs a 7.0.1 tag on frontend bundle)

Add first node deps

---

composer.json
composer.lock

It was wrongly placed in `require`.

Move mockery to dev dependencies

---

.travis.yml
composer.lock

Hopefully this will fix build errors.

Update distribution version

---

package.json
web/vendors/claroline/plugin/videorecorder/css/video-recorder.css

The UglifyPlugin from plugin from webpack has issues, so I implemented it as an additional build step.

Minify webpack dist in prod

---

web/vendors/claroline/plugin/videorecorder/css/video-recorder.css

Added by mistake in #880. Related to https://github.com/claroline/Distribution/issues/524.

Remove generated css file

---

npm-shrinkwrap.json

Needs claroline/Distribution#728 to be merged first.

Add eslint to shrinkwrap and update npm deps

---

composer.json
composer.lock

https://github.com/stefk/md
See claroline/Distribution#693

Add php linter

---

npm-shrinkwrap.json

Follows claroline/Distribution#757.

Add webpack import loader plugin

---

.travis.yml
composer.lock
npm-shrinkwrap.json
package.json

This will be needed when https://github.com/claroline/Distribution/pull/1152 is merged.

Add karma npm script + prod flag

---

npm-shrinkwrap.json

Added checklist-model dependency to npm for https://github.com/claroline/Distribution/pull/1174

Added checklist-model in npm

---

README.md

See https://github.com/claroline/Distribution/pull/1222

Document mbstring dependency

---

.travis.yml
README.md
composer.json
composer.lock

ping @ngodfraind, @stefk, @LaurentGruber.

Abandon support of PHP 5.5

---

package.json

Move dist npm dev deps to project root

---

npm-shrinkwrap.json
package.json

(build will fail because of renaming)

Update shrinkwrap + rename dist pkg

---

package.json

I forgot to update the "theme" command. Now adds the server directory here aswell.

Webpack extension

---

composer.json
composer.lock

Using the current installed versions.

fixes composer dependencies

---

package.json

Very useful for server side scripting: https://github.com/isaacs/node-glob

Add glob to dev deps

---

composer.json
composer.lock

To use with custom resource icons manager.
See PR here: https://github.com/claroline/Distribution/pull/2059

Added alternative repository for php-svg 

---

.gitignore
package.json

Replaces compilation script by the new one.

updates themes system

---

.docker/web/Dockerfile

Adds missing php extentions in the Docker web container
CC @ngodfraind, @ptsavdar

Fixes missing docker php extentions

---

npm-shrinkwrap.json

required by https://github.com/claroline/Distribution/pull/2612

adds react-router-dom

---

.travis.yml
app/config/parameters.yml.dist
composer.json
package.json

replaces : https://github.com/claroline/Claroline/pull/1232

changes installation process

---

npm-shrinkwrap.json
package.json

This is a `peerDep` of Webpack 3 and we cannot run `npm shrinkwrap` without it (which breaks jenkins builds)

adds missing dep in package.json

---

app/AppKernel.php
app/console

Les pbs d'install sont sans doute liés aux changement de sf3. La liste des bundles n'est plus la même.
Dans un premier temps je compte virer SwitchKernel (vu que ça fait plus rien).
Ce changement ne corrige rien mais standardifie un peu les choses.

Use standard sf kernel.

---

.gitignore
composer.json
package.json

Do not merge without https://github.com/claroline/Distribution/pull/5325.

upgrades to webpack 4

---

.travis.yml

* changes travis build env
* Update .travis.yml
* adds swap
* Update .travis.yml
* Update .travis.yml
* adds more swap

changes travis build env (#1496)

---

src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
src/main/core/Resources/modules/administration/community/group/store/reducer.js
src/main/core/Resources/modules/administration/community/location/store/reducer.js
src/main/core/Resources/modules/administration/community/organization/store/reducer.js
src/main/core/Resources/modules/administration/community/parameters/store/reducer.js
src/main/core/Resources/modules/administration/community/profile/store/reducer.js
src/main/core/Resources/modules/administration/community/role/store/reducer.js
src/main/core/Resources/modules/administration/community/user/store/actions.js
src/main/core/Resources/modules/administration/community/user/store/reducer.js
src/main/core/Resources/modules/plugin.js
src/main/core/Resources/modules/resource/modals/about/components/about.jsx
src/main/core/Resources/modules/tools/parameters/store/reducer.js
src/plugin/drop-zone/Resources/modules/resources/dropzone/correction/actions.js
src/plugin/drop-zone/Resources/modules/resources/dropzone/correction/reducer.js
src/plugin/drop-zone/Resources/modules/resources/dropzone/player/actions.js
src/plugin/drop-zone/Resources/modules/resources/dropzone/player/reducer.js
src/plugin/drop-zone/Resources/modules/resources/dropzone/store/actions.js
src/plugin/drop-zone/Resources/modules/resources/dropzone/store/index.js

fixes some js circular imports

---

.github/workflows/ci.yml
src/main/authentication/Tests/ClarolineAuthenticationBundleIntegrationTest.php

split github action jobs

---

src/plugin/formula/Controller/FormulaController.php

[Formula] fixes tinymce integration

---

src/main/app/Resources/modules/overlays/popover/components/overlay.jsx
src/main/core/API/Crud/WorkspaceCrud.php
src/main/core/Command/API/ImportCsvCommand.php
src/main/core/Listener/CliListener.php
src/main/core/Manager/UserManager.php
src/main/core/Manager/Workspace/Transfer/Tools/ResourceManager.php
src/main/core/Manager/Workspace/WorkspaceManager.php
src/main/core/Repository/WorkspaceRepository.php
src/main/core/Resources/config/services/command.yml
src/main/core/Resources/config/services/crud.yml
src/main/core/Resources/config/services/listener.yml
src/main/core/Resources/config/services/manager.yml
src/plugin/agenda/Crud/EventCrud.php
src/plugin/agenda/Resources/config/services/crud.yml
src/plugin/exo/Resources/modules/resources/quiz/overview/components/main.jsx
src/plugin/lesson/Installation/Migrations/pdo_mysql/Version20201006072423.php

fixes 13.x

---

src/main/core/Controller/APINew/ObjectLockController.php
src/main/core/Manager/LockManager.php
src/plugin/home/Controller/HomeController.php
src/plugin/home/Finder/HomeTabFinder.php
src/plugin/home/Resources/modules/tools/home/editor/components/tab.jsx
src/plugin/home/Resources/modules/tools/home/editor/modals/creation/store/actions.js

[Home] fixes tabs edition

---

src/main/core/Controller/APINew/LoggerController.php

[Transfer] fixes import logs

---

src/main/core/API/Transfer/Action/Workspace/RemoveUser.php
src/plugin/agenda/Entity/Event.php
src/plugin/home/Controller/HomeController.php
src/plugin/open-badge/Crud/BadgeClassCrud.php
src/plugin/open-badge/Serializer/BadgeClassSerializer.php

multiple fixes on 13.x

---

src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php

[Shortcut] fixes serialization

---

src/integration/big-blue-button/Controller/AdministrationController.php
src/integration/big-blue-button/Crud/BBBCrud.php
src/integration/big-blue-button/Finder/BBBFinder.php
src/integration/big-blue-button/Resources/config/services/crud.yml
src/integration/big-blue-button/Resources/modules/integration/bbb/components/resources.jsx
src/integration/big-blue-button/Resources/modules/integration/bbb/components/rooms.jsx
src/integration/big-blue-button/Resources/modules/integration/bbb/components/tool.jsx
src/integration/big-blue-button/Resources/modules/integration/bbb/containers/tool.jsx
src/integration/big-blue-button/Resources/modules/integration/bbb/store/actions.js
src/integration/big-blue-button/Resources/modules/integration/bbb/store/reducer.js
src/integration/big-blue-button/Resources/modules/integration/bbb/store/selectors.js
src/integration/big-blue-button/Resources/translations/bbb.en.json
src/integration/big-blue-button/Resources/translations/bbb.fr.json

[BigBlueButton] shows all bbb rooms in admin

---

src/main/core/Controller/FileController.php

The annotation used in the controller was removed.

fixes TinyMCE file upload

---

src/main/core/Resources/config/config.yml

[Resource] fixes copy permission

---

src/main/app/Resources/modules/content/components/message.jsx
src/main/core/Resources/modules/user/message/components/user-message-form.jsx
src/main/core/Resources/modules/user/message/components/user-message.jsx

adds ContentMessage component

---

.github/workflows/release_patch.yml

Release PR is created by github-actions, then approved and merged by Clarobot.

Fix release PR author/reviewer

---

src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
src/plugin/team/Controller/API/TeamController.php
src/plugin/team/Listener/Tool/TeamListener.php
src/plugin/team/Listener/UserListener.php
src/plugin/team/Manager/TeamManager.php
src/plugin/team/Resources/config/services/listener.yml
src/plugin/team/Serializer/TeamSerializer.php

[Team] fixes team serializer

---

src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json
src/plugin/cursus/Controller/CourseController.php
src/plugin/cursus/Crud/EventCrud.php
src/plugin/cursus/Entity/AbstractTraining.php
src/plugin/cursus/Entity/Course.php
src/plugin/cursus/Event/Log/LogSessionEventCreateEvent.php
src/plugin/cursus/Event/Log/LogSessionEventDeleteEvent.php
src/plugin/cursus/Event/Log/LogSessionEventEditEvent.php
src/plugin/cursus/Finder/CourseFinder.php
src/plugin/cursus/Installation/Migrations/pdo_mysql/Version20210210075649.php
src/plugin/cursus/Resources/modules/course/components/card.jsx
src/plugin/cursus/Resources/modules/course/components/form.jsx
src/plugin/cursus/Resources/modules/prop-types.js
src/plugin/cursus/Resources/modules/session/components/card.jsx
src/plugin/cursus/Resources/modules/session/components/form.jsx
src/plugin/cursus/Resources/modules/tools/trainings/catalog/components/list.jsx
src/plugin/cursus/Resources/translations/cursus.en.json
src/plugin/cursus/Resources/translations/cursus.fr.json
src/plugin/cursus/Resources/translations/cursus.nl.json
src/plugin/cursus/Serializer/CourseSerializer.php
src/plugin/cursus/Serializer/SessionSerializer.php

[Cursus] enhances plugin

---

src/main/core/Manager/LogConnectManager.php

fixes LogConnect for deleted workspaces

---

src/main/core/Entity/User.php
src/main/core/Manager/Workspace/WorkspaceManager.php

[Workspace] fixes view as

---

src/main/authentication/Installation/Updater/Updater130002.php

fixes ips migration

---

src/main/app/Resources/modules/content/components/title.jsx
src/main/app/Resources/modules/content/form/components/stepper.jsx
src/main/app/Resources/modules/security/registration/components/main.jsx
src/main/app/Resources/styles/type.less
src/main/app/Resources/translations/platform.en.json
src/main/app/Resources/translations/platform.fr.json
src/main/core/Resources/less/layout/components/gauges.less
src/main/core/Resources/less/layout/form/form-stepper.less
src/main/core/Resources/less/layout/form/index.less
src/main/core/Resources/less/tinymce/default/Variables.less

[UI] redraws form stepper (sm screens friendly)

---

src/main/app/API/Utils/ArrayUtils.php

[Scorm] fixes log rendering

---

src/main/app/Resources/modules/data/types/image/components/display.jsx
src/main/app/Resources/modules/data/types/image/index.js
src/main/app/Resources/styles/type.less
src/main/core/Resources/less/users/message.less

fixes images rendering

---

src/integration/big-blue-button/ClarolineBigBlueButtonBundle.php
src/main/core/ClarolineCoreBundle.php
src/main/core/DataFixtures/PostInstall/LoadTemplateData.php
src/main/core/DataFixtures/Required/LoadDefaultOrganizationData.php
src/main/core/DataFixtures/Required/LoadPlatformRolesData.php
src/main/core/Manager/Template/TemplateManager.php
src/main/installation/Bundle/InstallableBundle.php
src/main/installation/Bundle/InstallableInterface.php
src/main/installation/Fixtures/FixtureLoader.php
src/main/installation/Manager/InstallationManager.php
src/main/installation/Resources/config/services.yml
src/plugin/analytics/ClarolineAnalyticsBundle.php
src/plugin/booking/ClarolineBookingBundle.php
src/plugin/cursus/ClarolineCursusBundle.php
src/plugin/formula/IcapFormulaPluginBundle.php
src/plugin/home/ClarolineHomeBundle.php
src/plugin/image-player/ClarolineImagePlayerBundle.php
src/plugin/lti/UJMLtiBundle.php
src/plugin/message/ClarolineMessageBundle.php
src/plugin/open-badge/ClarolineOpenBadgeBundle.php
src/plugin/pdf-player/ClarolinePdfPlayerBundle.php
src/plugin/tag/ClarolineTagBundle.php
src/plugin/team/ClarolineTeamBundle.php
src/plugin/text-player/ClarolineTextPlayerBundle.php
src/plugin/video-player/ClarolineVideoPlayerBundle.php
src/plugin/web-resource/ClarolineWebResourceBundle.php

- enhances PHP typings.
- removes uneeded methods overrides.
- RequiredFixtures are now loaded during the update process too.

reworks data fixtures

---

src/main/app/API/Utils/ArrayUtils.php
src/main/core/Library/Configuration/PlatformConfigurationHandler.php

fixes platform_options default parameters

---

src/main/app/API/Crud.php

allows CRUD to update an existing entity

---

.github/workflows/release_patch.yml

Create release commits from clarobot

---

src/main/app/Resources/modules/data/types/address/components/input.jsx
src/main/app/Resources/modules/data/types/number/components/input.jsx

fixes some UI data types

---

src/plugin/path/Manager/UserProgressionManager.php

[Path] fixes progression update

---

src/plugin/path/Manager/UserProgressionManager.php

[Path] fixes score calculation

---

src/main/core/Resources/modules/tools/community/role/modals/rights/containers/modal.jsx

[Community] fixes role tools configuration

---

src/plugin/cursus/Resources/modules/course/components/form.jsx
src/plugin/cursus/Resources/modules/course/components/list.jsx
src/plugin/cursus/Resources/modules/course/components/main.jsx
src/plugin/cursus/Resources/modules/course/containers/form.jsx
src/plugin/cursus/Resources/modules/course/containers/main.jsx
src/plugin/cursus/Resources/modules/home/catalog/components/details.jsx
src/plugin/cursus/Resources/modules/home/catalog/components/form.jsx
src/plugin/cursus/Resources/modules/home/catalog/components/list.jsx
src/plugin/cursus/Resources/modules/home/catalog/components/parameters.jsx
src/plugin/cursus/Resources/modules/home/catalog/components/tab.jsx
src/plugin/cursus/Resources/modules/home/catalog/containers/details.jsx
src/plugin/cursus/Resources/modules/home/catalog/containers/form.jsx
src/plugin/cursus/Resources/modules/home/catalog/containers/tab.jsx
src/plugin/cursus/Resources/modules/home/catalog/index.js
src/plugin/cursus/Resources/modules/plugin.js
src/plugin/cursus/Resources/modules/tools/events/components/tool.jsx
src/plugin/cursus/Resources/modules/tools/trainings/catalog/components/details.jsx
src/plugin/cursus/Resources/modules/tools/trainings/catalog/components/form.jsx
src/plugin/cursus/Resources/modules/tools/trainings/catalog/components/list.jsx
src/plugin/cursus/Resources/translations/cursus.en.json
src/plugin/cursus/Resources/translations/cursus.fr.json
src/plugin/home/Resources/modules/home/widgets/components/tab.jsx
src/plugin/home/Resources/modules/tools/home/components/page.jsx
src/plugin/home/Resources/modules/tools/home/components/tabs.jsx
src/plugin/home/Resources/modules/tools/home/editor/components/tab.jsx
src/plugin/home/Resources/modules/tools/home/editor/store/selectors.js
src/plugin/home/Resources/modules/tools/home/player/components/tab.jsx
src/plugin/home/Resources/modules/tools/home/player/store/selectors.js
src/plugin/home/Resources/modules/tools/home/utils.js

[Cursus] implements catalog home tab

---

src/plugin/blog/Resources/modules/resources/blog/index.js
src/plugin/blog/Resources/translations/actions.en.json
src/plugin/blog/Resources/translations/actions.fr.json

[Blog] sets default rights on resource create

---

src/plugin/path/Resources/modules/resources/path/player/components/main.jsx

[Path] fixes nav btn not shown after navigation

---

src/main/app/Resources/modules/layout/sections/desktop/components/main.jsx
src/main/app/Resources/modules/layout/sections/desktop/components/menu.jsx
src/main/app/Resources/translations/platform.en.json
src/main/app/Resources/translations/platform.fr.json
src/main/core/Controller/DesktopController.php
src/main/core/Controller/WorkspaceController.php
src/main/core/Manager/Tool/ToolManager.php
src/main/core/Resources/config/services/controller.yml
src/main/core/Resources/modules/tool/components/main.jsx
src/main/core/Resources/modules/tool/containers/main.jsx
src/main/core/Resources/modules/tool/store/actions.js
src/main/core/Resources/modules/tool/store/reducer.js
src/main/core/Resources/modules/tool/store/selectors.js
src/main/core/Resources/modules/workspace/components/main.jsx
src/main/core/Resources/modules/workspace/components/menu.jsx
src/main/core/Resources/translations/tools.en.json
src/main/core/Resources/translations/tools.fr.json

enhances tool accesses management

---

src/main/core/Event/CatalogEvents/SecurityEvents.php
src/main/core/Manager/Workspace/WorkspaceManager.php

fixes log namespace

---

src/main/authentication/Resources/modules/header/authentication/components/menu.jsx
src/main/authentication/Resources/modules/header/authentication/containers/menu.jsx
src/main/authentication/Resources/modules/header/authentication/index.js
src/main/authentication/Resources/modules/plugin.js
src/main/core/Library/Configuration/PlatformDefaults.php

[Authentication] adds header widget

---

src/main/authentication/Resources/modules/account/tokens/components/main.jsx
src/main/authentication/Resources/modules/integration/tokens/components/tool.jsx
src/main/authentication/Serializer/ApiTokenSerializer.php
src/main/core/API/Serializer/User/UserSerializer.php

[Authentication] adds tokens export

---

src/main/app/Resources/modules/page/components/full.jsx
src/main/app/Resources/modules/page/components/header.jsx
src/main/app/Resources/modules/page/prop-types.js
src/plugin/home/Entity/HomeTabConfig.php
src/plugin/home/Installation/Migrations/pdo_mysql/Version20210309110541.php
src/plugin/home/Resources/modules/tools/home/components/page.jsx
src/plugin/home/Resources/modules/tools/home/editor/components/form.jsx
src/plugin/home/Resources/translations/home.en.json
src/plugin/home/Resources/translations/home.fr.json
src/plugin/home/Serializer/HomeTabSerializer.php

[Home] adds option to hide tab title

---

src/main/app/Resources/modules/security/login/components/form.jsx
src/main/app/Resources/modules/security/login/containers/form.jsx
src/main/core/API/Serializer/Platform/ClientSerializer.php
src/main/core/Library/Configuration/PlatformDefaults.php
src/main/core/Resources/modules/administration/community/parameters/components/parameters-tab.jsx

[Authentication] adds custom message on login page

---

src/main/app/Resources/modules/security/login/components/form.jsx
src/main/app/Resources/modules/security/login/containers/form.jsx
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json

[Login] use platform name in translations

---

src/main/authentication/Security/Logout/LogoutHandler.php

[Saml] fixes logout

---

src/main/app/Resources/modules/layout/sections/home/components/main.jsx
src/main/app/Resources/modules/layout/sections/home/containers/main.jsx
src/main/app/Resources/modules/security/login/components/form.jsx
src/main/app/Resources/modules/security/login/containers/form.jsx
src/main/core/API/Serializer/Platform/ClientSerializer.php
src/main/core/Library/Configuration/PlatformDefaults.php
src/main/core/Resources/modules/administration/community/parameters/components/parameters-tab.jsx
src/main/core/Resources/modules/user/actions/password-change.js
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json

[Authentication] adds option to allow/disallow password changes

---

src/plugin/url/Resources/modules/components/form.jsx
src/plugin/url/Resources/translations/url.en.json
src/plugin/url/Resources/translations/url.fr.json

[Url] fixes #1610

---

src/main/app/Resources/modules/content/search/components/unified.jsx
src/plugin/scorm/Finder/ScoTrackingFinder.php
src/plugin/scorm/Manager/ScormManager.php
src/plugin/scorm/Resources/modules/resources/scorm/player/components/results.jsx

[Scorm] multiple fixes

---

src/plugin/forum/Resources/config/config.yml

[Forum] fixes missing post right

---

src/plugin/video-player/Resources/modules/files/video/components/player.jsx
src/plugin/video-player/Resources/styles/files/video.less

[Video] fixes video unmount

---

src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/plugin/announcement/Serializer/AnnouncementSerializer.php
src/plugin/home/Controller/HomeController.php
src/plugin/home/Entity/HomeTab.php
src/plugin/home/Finder/HomeTabFinder.php
src/plugin/home/Listener/Tool/HomeListener.php
src/plugin/home/Manager/HomeManager.php
src/plugin/home/Resources/config/services/controller.yml
src/plugin/home/Resources/config/services/finder.yml
src/plugin/home/Resources/config/services/listener.yml
src/plugin/home/Resources/config/services/manager.yml
src/plugin/home/Security/Voter/HomeTabVoter.php
src/plugin/home/Serializer/HomeTabSerializer.php

[Home] fixes tab restrictions

---

src/plugin/lesson/Finder/ChapterFinder.php
src/plugin/lesson/Resources/modules/resources/lesson/components/resource.jsx

[Lesson] enhances search

---

src/plugin/exo/Resources/modules/items/choice/components/paper.jsx

[Quiz] fixes statistics

---

package.json

fixes npm dependencies

---

src/main/app/Resources/modules/data/types/choice/index.js
src/main/app/Resources/modules/input/components/radios.jsx
src/main/app/Resources/modules/layout/menu/store/actions.js
src/main/app/Resources/modules/layout/sections/administration/store/actions.js
src/main/app/Resources/modules/layout/sections/desktop/store/actions.js
src/main/app/Resources/modules/layout/sections/home/components/main.jsx
src/main/app/Resources/modules/layout/sections/home/containers/main.jsx
src/main/app/Resources/modules/layout/sections/home/store/actions.js
src/main/app/Resources/modules/layout/sections/home/store/index.js
src/main/core/API/Serializer/Platform/ClientSerializer.php
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Library/Configuration/PlatformDefaults.php
src/main/core/Manager/Workspace/WorkspaceManager.php
src/main/core/Resources/modules/administration/parameters/main/components/meta.jsx
src/main/core/Resources/modules/workspace/components/form.jsx
src/main/core/Resources/modules/workspace/store/actions.js
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.es.json
src/main/core/Resources/translations/platform.fr.json
src/main/core/Resources/translations/platform.nl.json
src/main/theme/Resources/modules/administration/appearance/ui/components/main.jsx

adds option to toggle menu in all contexts

---

src/plugin/lesson/Resources/modules/resources/lesson/components/menu.jsx
src/plugin/lesson/Resources/modules/resources/lesson/containers/menu.jsx
src/plugin/lesson/Resources/modules/resources/lesson/store/actions.js

[Lesson] fixes pdf export of chapters

---

src/plugin/home/Resources/modules/tools/home/editor/components/tab.jsx
src/plugin/home/Security/Voter/HomeTabVoter.php

[Home] fixes rights check

---

src/plugin/cursus/Resources/modules/course/components/sessions.jsx
src/plugin/cursus/Resources/modules/course/containers/sessions.jsx
src/plugin/cursus/Resources/modules/tools/trainings/catalog/components/form.jsx

[Training] fixes form redirections

---

src/plugin/cursus/Manager/SessionManager.php

[Training] fixes DI

---

src/plugin/cursus/Resources/modules/data/sources/sessions.js

[Training] fixes public session data source

---

src/main/app/API/Crud.php
src/main/core/Manager/Workspace/TransferManager.php

fixes workspace creation

---

src/plugin/lesson/Resources/translations/log.en.json
src/plugin/lesson/Resources/translations/log.fr.json
src/plugin/lesson/Resources/views/log/log_list_item.html.twig

[Lesson] fixes logs display

---

src/plugin/drop-zone/Controller/API/DropController.php
src/plugin/drop-zone/Listener/Resource/DropzoneListener.php
src/plugin/drop-zone/Manager/DropzoneManager.php
src/plugin/drop-zone/Resources/modules/resources/dropzone/overview/components/overview.jsx
src/plugin/drop-zone/Resources/modules/resources/dropzone/overview/components/timeline.jsx
src/plugin/drop-zone/Resources/modules/resources/dropzone/store/selectors.js
src/plugin/drop-zone/Resources/translations/dropzone.fr.json

[Dropzone] fixes statuses and evaluation start

---

src/main/core/Resources/views/log/view_details.html.twig
src/main/core/Resources/views/log/view_details_action_resource_update_rename.html.twig
src/main/core/Resources/views/log/view_list_item.html.twig
src/main/core/Resources/views/log/view_list_item_label.html.twig
src/plugin/blog/Resources/views/log/log_details.html.twig
src/plugin/blog/Resources/views/log/log_list_item.html.twig
src/plugin/drop-zone/Resources/views/log/log_details.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_correction.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_correction_delete.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_correction_end.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_correction_start.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_correction_update.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_correction_validation_change.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_document_create.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_document_delete.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_document_open.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_drop_end.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_drop_evaluate.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_drop_grade_available.html.twig
src/plugin/drop-zone/Resources/views/log/log_details_drop_report.html.twig
src/plugin/drop-zone/Resources/views/log/log_list_item.html.twig
src/plugin/exo/Resources/views/log/show.html.twig
src/plugin/lesson/Resources/views/log/log_details.html.twig
src/plugin/social-media/Resources/views/log/log_details.html.twig
src/plugin/social-media/Resources/views/log/log_list_item.html.twig
src/plugin/wiki/Resources/views/log/log_details.html.twig
src/plugin/wiki/Resources/views/log/log_list_item.html.twig
src/plugin/wiki/Resources/views/wiki/pdf.html.twig

fixes twig templates naming

---

public/index.php
public/maintenance.php

It just restores the feature like it was in the previous versions.

fixes platform no longer disabled in maintenance mode

---

src/integration/big-blue-button/Controller/BBBController.php
src/integration/big-blue-button/Resources/config/services/voter.yml
src/integration/big-blue-button/Security/Voter/RecordingVoter.php

[BigBlueButton] fixes rights check on recording delete

---

src/plugin/scorm/Controller/ScormController.php
src/plugin/scorm/Entity/Scorm.php
src/plugin/scorm/Listener/ScormListener.php
src/plugin/scorm/Manager/ScormManager.php
src/plugin/scorm/Resources/config/config.yml
src/plugin/scorm/Resources/config/services/listener.yml

[Scorm] allows to change resource file

---

bin/console

Fix maintenance mode not automatically enabled on platform update

---

bin/console

Fix typo in bin/console

---

src/integration/big-blue-button/Controller/BBBController.php
src/integration/big-blue-button/Crud/BBBCrud.php
src/integration/big-blue-button/Manager/BBBManager.php
src/integration/big-blue-button/Resources/config/services/crud.yml
src/integration/big-blue-button/Resources/modules/resources/bbb/editor/components/editor.jsx
src/integration/big-blue-button/Resources/modules/resources/bbb/player/components/player.jsx
src/integration/big-blue-button/Resources/translations/bbb.en.json
src/integration/big-blue-button/Resources/translations/bbb.fr.json

[BigBlueButton] allows to change server after first attribution

---

src/main/core/Controller/AdministrationController.php
src/main/core/Controller/DesktopController.php
src/main/core/Controller/WorkspaceController.php
src/main/core/Event/Tool/OpenToolEvent.php
src/main/core/Subscriber/Log/FunctionalLogSubscriber.php

fixes tool opening for anonymous tokens

---

src/main/core/Resources/config/services/manager.yml
src/plugin/agenda/Resources/config/services/serializer.yml
src/plugin/agenda/Serializer/EventSerializer.php
src/plugin/agenda/Serializer/TaskSerializer.php

[Agenda] fixes event creation in workspaces

---

src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
src/main/core/Entity/Resource/ResourceNode.php
src/main/core/Installation/Migrations/pdo_mysql/Version20210428042821.php
src/main/core/Resources/modules/resource/components/form.jsx
src/main/core/Resources/modules/resource/components/page.jsx
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json
src/plugin/home/Resources/translations/home.en.json
src/plugin/home/Resources/translations/home.fr.json

adds option to hide resource title

---

src/main/app/API/TransferProvider.php
src/main/app/API/ValidatorInterface.php
src/main/app/API/ValidatorProvider.php
src/main/app/DependencyInjection/Compiler/ApiConfigPass.php
src/main/app/Resources/config/services.yml
src/main/core/API/Validator/GroupValidator.php
src/main/core/API/Validator/Resource/ResourceNodeValidator.php
src/main/core/API/Validator/UserValidator.php
src/main/core/API/Validator/WorkspaceValidator.php
src/plugin/message/Validator/MessageValidator.php

lazy load validators

---

src/main/core/Resources/modules/plugin.js
src/main/core/Resources/modules/tool/actions/configure.js
src/main/core/Resources/modules/tool/actions/rights.js
src/main/core/Resources/modules/tool/components/main.jsx
src/main/core/Resources/modules/tool/components/page.jsx
src/main/core/Resources/modules/tool/containers/page.jsx
src/main/core/Resources/modules/tool/modals/rights/components/modal.jsx
src/main/core/Resources/modules/tool/modals/rights/containers/modal.jsx
src/main/core/Resources/modules/tool/utils.js

allows to inject tool actions from plugins

---

src/plugin/audio-player/Library/Quiz/Item/Definition/WaveformDefinition.php
src/plugin/audio-player/Resources/modules/quiz/items/waveform/components/feedback.jsx
src/plugin/audio-player/Resources/modules/quiz/items/waveform/components/paper.jsx
src/plugin/audio-player/Resources/modules/quiz/items/waveform/index.js
src/plugin/audio-player/Resources/modules/quiz/items/waveform/utils.js

[Audio] fixes waveform question

---

src/main/recorder/Handler/BundleHandler.php

auto register new plugins

---

src/main/app/Resources/modules/layout/sections/home/components/login.jsx
src/main/app/Resources/modules/layout/sections/home/components/registration.jsx
src/main/core/Listener/AuthenticationSuccessListener.php
src/main/core/Resources/config/services/listener.yml
src/main/core/Resources/modules/workspace/components/main.jsx
src/main/core/Resources/modules/workspace/components/restrictions.jsx
src/main/core/Resources/modules/workspace/store/actions.js

- Redirect to last url only if it's part of the claroline platform.
- Fix login modal which doesn't close correctly in workspaces

fixes login

---

src/plugin/home/Manager/HomeManager.php
src/plugin/home/Manager/Workspace/Transfer/Home.php
src/plugin/home/Resources/config/services/manager.yml
src/plugin/home/Serializer/HomeTabSerializer.php

[Home] fixes workspace copy

---

src/plugin/open-badge/Security/Voter/BadgeClassVoter.php

[Badge] fixes rights checks

---

src/main/core/Command/User/DisableInactiveCommand.php
src/main/core/Repository/User/UserRepository.php
src/main/core/Resources/config/services/command.yml

[Community] adds cmd to disable inactive users

---

src/main/core/API/Finder/Resource/ResourceNodeFinder.php
src/plugin/agenda/Finder/AbstractEventFinder.php

[Agenda] fixes event finder sorting

---

src/main/app/API/Options.php
src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
src/main/core/Controller/APINew/Resource/ResourceNodeController.php
src/main/core/Listener/Resource/ResourceListener.php
src/main/core/Manager/Resource/RightsManager.php
src/main/core/Manager/ResourceManager.php
src/main/core/Manager/Workspace/Transfer/Tools/ResourceManager.php
src/main/core/Resources/modules/resource/actions/rights.js
src/main/core/Resources/modules/resource/modals/rights/components/modal.jsx
src/main/core/Resources/modules/resource/modals/rights/containers/modal.jsx
src/main/core/Resources/modules/resource/modals/rights/store/actions.js
src/main/core/Resources/translations/resource.en.json
src/main/core/Resources/translations/resource.fr.json

[Resource] only loads rights when needed

---

src/main/core/Manager/Workspace/Transfer/Tools/ResourceManager.php

[Resource] fixes transfer

---

src/plugin/notification/Listener/Tool/NotificationListener.php
src/plugin/notification/Resources/config/services/listener.yml

[Notification] fixes tool opening

---

src/plugin/tag/Serializer/TagSerializer.php

[Tag] fixes tag update

---

src/plugin/message/Manager/MessageManager.php
src/plugin/message/Subscriber/MessageSubscriber.php

[Message] removes obsolete param

---

src/plugin/tag/Listener/TagListener.php

[Tag] fixes list filter

---

src/main/core/API/Transfer/Action/User/SetMainOrganization.php
src/main/core/API/Validator/UserValidator.php
src/main/core/Resources/config/services/transfer.yml
src/main/core/Resources/samples/user/csv/valid/set_main_organization/by_email.csv
src/main/core/Resources/samples/user/csv/valid/set_main_organization/by_id.csv
src/main/core/Resources/samples/user/csv/valid/set_main_organization/by_username.csv
src/main/core/Resources/translations/transfer.en.json
src/main/core/Resources/translations/transfer.fr.json

[Transfer] adds action to set users main organization

---

src/main/core/API/Crud/Resource/ResourceNodeCrud.php
src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
src/main/core/Manager/Resource/ResourceLifecycleManager.php
src/main/core/Manager/ResourceManager.php

[Resource] removes generation of unique names

---

src/main/app/API/TransferProvider.php

[Transfer] handles BOM in csv files

---

src/plugin/home/Resources/styles/home.less

[Home] fixes styles when there are lots of tabs

---

src/main/app/Resources/modules/config/asset.js

fixes ui assets path

---

src/main/app/Resources/modules/config/theme.js
src/main/app/Resources/modules/intl/translation/translator.js

It uses platform version as a dumb cache buster.

adds cache busting for translations and themes

---

src/main/core/Controller/APINew/Platform/ParametersController.php

exposes platform version in api

---

src/main/core/Entity/Facet/FieldFacetValue.php
src/main/core/Installation/Migrations/pdo_mysql/Version20210526121331.php
src/plugin/claco-form/Finder/EntryFinder.php

[ClacoForm] fixes entries search

---

src/plugin/agenda/Manager/EventManager.php

[Agenda] sends invitation when a participant is added

---

src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
src/main/core/Resources/modules/resource/components/form.jsx

[Resource] fixes node edition

---

src/plugin/agenda/DataFixtures/PostInstall/LoadTemplateData.php

[Agenda] fixes template insert

---

src/plugin/cursus/Finder/EventFinder.php

[Trainings] fixes workspace events tool

---

src/plugin/agenda/Finder/AbstractEventFinder.php
src/plugin/agenda/Resources/config/services/finder.yml

[Agenda] fixes data sources

---

src/plugin/drop-zone/Serializer/DocumentSerializer.php

[Dropzone] fixes drops with deleted resources

---

src/main/app/API/FinderProvider.php
src/main/core/API/Finder/User/UserFinder.php

fixes searches with numeric strings

---

src/main/app/Resources/modules/intl/date/index.js
src/plugin/cursus/Entity/Course.php
src/plugin/cursus/Installation/Migrations/pdo_mysql/Version20210601072555.php
src/plugin/cursus/Resources/schemas/course.json

| BC breaks?    | ???
| Fixed issues | space between currency and value
- Allow to put a decimal number as duration of course
- Improve the display of "long" duration to add space between the value and unit

[Trainings] allows float for session duration

---

src/main/core/Entity/Planning/Planning.php

fixes planning creation

---

src/plugin/cursus/Resources/modules/course/components/about.jsx

[Trainings] fixes price description rendering

---

src/main/core/Command/Logs/LogsFetcherCommand.php

[Logs] adds param to export command

---

src/main/app/Resources/modules/intl/date/index.js

| BC breaks?    | ???
Change the display of duration.

Change display of duration

---

src/plugin/cursus/Finder/EventFinder.php
src/plugin/cursus/Listener/DataSource/EventsSource.php
src/plugin/cursus/Listener/DataSource/SessionEventsSource.php
src/plugin/cursus/Repository/SessionRepository.php
src/plugin/cursus/Resources/config/config.yml
src/plugin/cursus/Resources/config/services/listener.yml
src/plugin/cursus/Resources/modules/data/sources/session-events.js
src/plugin/cursus/Resources/modules/plugin.js
src/plugin/cursus/Resources/translations/data_sources.en.json
src/plugin/cursus/Resources/translations/data_sources.fr.json

| BC breaks?    | ???
Add data source for display all events of session.
Not done !!!

Session events

---

src/main/core/Resources/less/data/card.less
src/main/core/Resources/less/data/user.less
src/main/core/Resources/less/users/index.less
src/main/core/Resources/modules/data/types/users/components/cell.jsx
src/main/core/Resources/modules/user/components/micro-list.jsx
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json
src/plugin/cursus/Listener/DataSource/EventsSource.php
src/plugin/cursus/Repository/SessionRepository.php
src/plugin/cursus/Resources/config/config.yml
src/plugin/cursus/Resources/config/services/listener.yml
src/plugin/cursus/Resources/config/services/serializer.yml
src/plugin/cursus/Resources/modules/data/sources/events.js
src/plugin/cursus/Resources/modules/data/sources/my-sessions.js
src/plugin/cursus/Resources/modules/data/sources/sessions.js
src/plugin/cursus/Resources/modules/event/components/card.jsx
src/plugin/cursus/Resources/modules/event/components/list.jsx
src/plugin/cursus/Resources/modules/plugin.js
src/plugin/cursus/Resources/modules/session/components/list.jsx
src/plugin/cursus/Resources/translations/data_sources.en.json
src/plugin/cursus/Resources/translations/data_sources.fr.json
src/plugin/cursus/Serializer/EventSerializer.php
src/plugin/cursus/Serializer/SessionSerializer.php

[Training] enhances events display

---

.docker/web/entrypoint.sh
docker-compose.yml

Also, remove the ./src volume from the prod build as we have a dev build now where the entire application is a volume

[docker] fix upgrade commands, rebuild theme upon re-run

---

src/main/core/Controller/APINew/User/OrganizationController.php

fixes #1727

---

src/main/app/Resources/modules/content/components/restriction.jsx
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Entity/Workspace/Workspace.php
src/main/core/Installation/Migrations/pdo_mysql/Version20210615073733.php
src/main/core/Resources/modules/workspace/components/form.jsx
src/main/core/Resources/modules/workspace/components/restrictions.jsx
src/main/core/Resources/modules/workspace/modals/about/components/about.jsx
src/main/core/Resources/modules/workspace/prop-types.js
src/main/core/Resources/translations/workspace.en.json
src/main/core/Resources/translations/workspace.fr.json

[Workspace] adds contact email

---

src/main/app/Resources/modules/intl/date/index.js
src/main/app/Resources/modules/intl/index.js
src/plugin/agenda/Resources/modules/event/components/card.jsx
src/plugin/cursus/Resources/modules/event/components/card.jsx

fixes timezone in date ranges display

---

src/main/core/Resources/modules/account/privacy/index.js
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json
src/main/log/Finder/FunctionalLogFinder.php
src/main/log/Finder/MessageLogFinder.php
src/main/log/Finder/SecurityLogFinder.php
src/main/log/Resources/config/config.yml
src/main/log/Resources/config/services/finder.yml
src/main/log/Resources/config/services/serializer.yml
src/main/log/Resources/modules/account/functional/components/list.jsx
src/main/log/Resources/modules/account/security/components/list.jsx
src/main/log/Resources/modules/administration/logs/components/functional.jsx
src/main/log/Resources/modules/administration/logs/components/log.jsx
src/main/log/Resources/modules/administration/logs/components/message.jsx
src/main/log/Serializer/FunctionalLogSerializer.php
src/main/log/Serializer/MessageLogSerializer.php
src/main/log/Serializer/SecurityLogSerializer.php
src/main/log/Subscriber/Administration/LogsSubscriber.php

[Log] fixes ui and di

---

src/main/core/API/Serializer/Platform/ClientSerializer.php
src/main/core/Library/Configuration/PlatformConfigurationHandler.php
src/plugin/saml/Listener/Platform/SamlSsoListener.php

[Saml] fixes sso button

---

src/main/app/Controller/Platform/ClientController.php
src/main/app/Resources/modules/layout/index.js
src/main/app/Resources/modules/security/login/components/form.jsx
src/main/app/Resources/modules/security/login/containers/form.jsx
src/main/app/Resources/modules/security/login/store/selectors.js
src/main/app/Resources/modules/security/store/reducer.js
src/main/app/Resources/modules/security/store/selectors.js
src/main/app/Resources/views/index.html.twig
src/main/authentication/Configuration/PlatformDefaults.php
src/main/authentication/Listener/Platform/OauthSsoListener.php
src/main/core/Entity/Log/AbstractLog.php
src/main/core/Resources/less/layout/header.less
src/main/core/Resources/less/users/authentication.less
src/main/log/Resources/config/services/subscriber.yml
src/main/log/Resources/modules/account/security/components/list.jsx
src/main/log/Resources/modules/administration/logs/components/log.jsx
src/main/log/Subscriber/FunctionalLogSubscriber.php
src/main/log/Subscriber/SecurityLogSubscriber.php

Ips management

---

src/main/core/Resources/schemas/location.json

fixes #1746

---

src/plugin/cursus/Finder/EventFinder.php

[Training] fixes events list sort

---

src/main/core/Resources/modules/layout/calendar/components/calendar.jsx
src/main/core/Resources/modules/layout/calendar/components/view/days.jsx

| BC breaks?    | ???
| Fixed issues | disabled of "end date"
Two small commits for round minutes in step number (for decrement & increment minute).
Now the user can select the same start date & end date in calendar.

Improve calendar

---

src/main/app/Controller/Platform/ClientController.php
src/main/core/Library/Configuration/PlatformConfigurationHandler.php

fixes ips checks in config

---

src/main/core/Controller/APINew/User/RegistrationController.php
src/main/core/Installation/AdditionalInstaller.php
src/main/core/Installation/Updater/Updater130023.php
src/main/core/Resources/config/services/updater.yml
src/main/core/Resources/config/services/voter.yml
src/main/core/Security/Voter/OrganizationVoter.php

- Adds missing migration for the old param.
- Fixes checks still using the old param

[Community] fixes param for organization selection on registration

---

src/main/authentication/Resources/config/suggested/hwi_oauth.yml
src/main/core/Listener/AuthenticationSuccessListener.php
src/main/core/Resources/config/suggested/security_prod.yml
src/plugin/saml/Controller/AuthenticationController.php
src/plugin/saml/Resources/config/suggested/light_saml_symfony_bridge.yml

[Saml] fixes redirection after login

---

src/main/core/Resources/schemas/user.json
src/plugin/saml/Security/UserCreator.php

[Saml] fixes user creation

---

src/main/core/Listener/AuthenticationSuccessListener.php

[Authentication] fixes redirection

---

src/main/core/ClarolineCoreBundle.php
src/main/core/DependencyInjection/Compiler/GeoipPass.php
src/main/core/Tests/DependencyInjection/Compiler/GeoipPassTest.php

Remove MaxmindGeoipInfoProvider service when the database file is not present

---

src/plugin/home/Resources/modules/tools/home/editor/components/form.jsx

Increment the limit of length of title tab to 64 characters.

[Home] Increment limit of title tab

---

src/main/core/Resources/modules/modals/groups/components/modal.jsx

fixes #1741

---

src/plugin/exo/Controller/AnalyticsController.php

[Quiz] fixes attempts chart

---

src/plugin/exo/Resources/modules/resources/quiz/editor/validation.js

[Quiz] fixes max attempts form validation

---

src/main/installation/Repository/UpdaterExecutionRepository.php
src/plugin/home/Installation/Migrations/pdo_mysql/Version20201117064352.php

fixes upgrade from 12.5

---

.docker.dev/web/Dockerfile

Add script in docker-container for check and fix your code before the workflow.
I have to improve it but it's a begin.

Check & fix code in dev

---

src/main/app/Resources/modules/layout/header/components/user.jsx
src/main/app/Resources/modules/layout/sections/home/components/external-account.jsx
src/main/app/Resources/modules/layout/sections/home/components/menu.jsx
src/main/app/Resources/modules/security/login/components/form.jsx
src/main/app/Resources/modules/security/registration/components/main.jsx
src/main/app/Resources/translations/actions.en.json
src/main/app/Resources/translations/actions.fr.json
src/main/authentication/Resources/modules/header/authentication/components/menu.jsx

renames platform registration buttons

---

src/main/core/API/Finder/Planning/PlannedObjectFinder.php
src/main/core/Controller/APINew/Location/MaterialController.php
src/main/core/Controller/APINew/Location/RoomController.php
src/main/core/Resources/modules/tools/locations/room/components/details.jsx
src/main/core/Resources/modules/tools/locations/room/containers/details.jsx
src/main/core/Resources/modules/tools/locations/room/containers/page.jsx
src/main/core/Resources/modules/tools/locations/room/store/reducer.js

fixes #1788

---

src/main/app/API/Crud.php
src/main/app/Controller/AbstractCrudController.php
src/main/app/Resources/config/services.yml
src/main/core/API/Finder/Workspace/EvaluationFinder.php
src/main/core/Controller/APINew/Workspace/EvaluationController.php
src/main/core/Resources/config/services/controller.yml
src/main/core/Resources/modules/data/types/workspaces/components/filter.jsx
src/main/core/Resources/modules/data/types/workspaces/index.js
src/plugin/analytics/Resources/modules/administration/dashboard/components/menu.jsx
src/plugin/analytics/Resources/modules/administration/dashboard/components/tool.jsx
src/plugin/analytics/Resources/modules/administration/dashboard/components/workspaces.jsx
src/plugin/analytics/Resources/modules/administration/dashboard/containers/workspaces.jsx
src/plugin/analytics/Resources/modules/administration/dashboard/store/reducer.js

allows to export user evaluations by workspaces

---

src/main/core/Controller/APINew/Model/HasGroupsTrait.php
src/main/core/Controller/APINew/Model/HasOrganizationsTrait.php
src/main/core/Controller/APINew/Model/HasParentTrait.php
src/main/core/Controller/APINew/Model/HasRolesTrait.php
src/main/core/Controller/APINew/Model/HasUsersTrait.php
src/main/core/Controller/APINew/Model/HasWorkspacesTrait.php
src/main/core/Controller/APINew/Workspace/WorkspaceController.php
src/main/core/Resources/modules/workspace/actions/archive.js
src/plugin/message/Controller/MessageController.php

[Workspaces] allows to archive models

---

src/plugin/scorm/Resources/modules/resources/scorm/player/api.js

[Scorm] adds logs for scorm api calls

---

src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json
src/plugin/exo/Resources/modules/charts/attempts/components/chart.jsx
src/plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
src/plugin/exo/Resources/modules/resources/quiz/editor/components/parameters.jsx
src/plugin/exo/Resources/modules/resources/quiz/overview/components/main.jsx
src/plugin/exo/Resources/translations/quiz.en.json
src/plugin/exo/Resources/translations/quiz.fr.json

[Quiz] enhances attempts chart

---

src/main/core/Resources/less/content/forbidden.less
src/main/core/Resources/less/content/loader.less
src/main/core/Resources/less/content/not-found.less
src/main/core/Resources/less/tinymce/default/Content.less
src/main/core/Resources/less/tinymce/default/Variables.less

Also fixes some tinymce override.

fixes theme variables

---

src/main/app/API/Crud.php
src/main/app/Resources/modules/api/router/index.js
src/main/core/Controller/APINew/Workspace/EvaluationController.php
src/main/core/Resources/modules/tools/community/user/components/tab.jsx
src/main/core/Resources/modules/tools/community/user/containers/tab.jsx

[Community] adds more columns in csv export

---

src/plugin/claco-form/Controller/ClacoFormController.php

[ClacoForm] uses human readable filenames in export

---

src/main/app/Persistence/ObjectManager.php
src/main/core/API/Transfer/Action/Directory/CreateOrUpdate.php
src/main/core/Manager/Workspace/TransferManager.php
src/main/core/Tests/Unit/Persistence/ObjectManagerTest.php

[Transfer] allows slug for directory update

---

src/main/core/Resources/modules/administration/community/user/components/users.jsx
src/main/core/Resources/modules/user/actions/enable.js

[Community] only allow to delete disabled users

---

src/plugin/announcement/Resources/modules/resources/announcement/components/announce.jsx

[Announces] fixes receivers list

---

src/plugin/path/Entity/Step.php
src/plugin/path/Installation/Migrations/pdo_mysql/Version20210903090000.php

[Path] fixes duplicate step slugs

---

src/main/core/Controller/APINew/Workspace/RequirementsController.php
src/main/core/Manager/Workspace/EvaluationManager.php

[Workspace] fixes evaluation status

---

src/plugin/cursus/Resources/config/config.yml

[Trainings] allows all courses data sources in ws

---

src/main/core/API/Transfer/Action/Directory/CreateOrUpdate.php

[Transfer] adds recursive rights param in dir import

---

src/main/core/Event/Log/LogResourceCopyEvent.php
src/main/core/Event/Log/LogResourceCreateEvent.php
src/main/core/Event/Log/LogResourceCustomEvent.php
src/main/core/Event/Log/LogResourceExportEvent.php
src/main/core/Event/Log/LogResourceMoveEvent.php
src/main/core/Event/Log/LogResourcePublishEvent.php
src/main/core/Event/Log/LogResourceUpdateEvent.php

[Log] fixes logs for node without creator

---

src/plugin/blog/Controller/PostController.php

[Blog] fixes posts edition

---

src/plugin/path/Manager/UserProgressionManager.php

[Path] fixes attempt updates on resource evaluation

---

src/main/core/API/Finder/Workspace/EvaluationFinder.php

[Workspace] hides evaluations of deleted/disabled users

---

src/main/core/Controller/APINew/Planning/PlannedObjectController.php
src/main/core/Entity/Planning/AbstractPlanned.php
src/main/core/Entity/Planning/PlannedObject.php
src/main/core/Installation/Migrations/pdo_mysql/Version20210908090043.php
src/main/core/Resources/config/services/voter.yml
src/main/core/Security/Voter/Planning/PlannedObjectVoter.php
src/plugin/agenda/Resources/config/services/voter.yml
src/plugin/agenda/Security/Voter/AbstractEventVoter.php
src/plugin/agenda/Security/Voter/TaskVoter.php

[Agenda] fixes rights

---

src/plugin/agenda/Installation/Migrations/pdo_mysql/Version20210406053510.php

[Agenda] fixes migration

---

src/plugin/blog/Manager/BlogManager.php

[Blog] fixes parameters update

---

src/main/core/API/Crud/User/UserCrud.php
src/main/core/API/Validator/UserValidator.php
src/main/core/Resources/config/services/crud.yml
src/main/core/Resources/config/services/validator.yml

[Community] fixes user defaults for mailNotified and mailValidated

---

src/main/app/Controller/Platform/ClientController.php
src/main/app/Resources/modules/layout/header/components/main.jsx
src/main/app/Resources/modules/layout/header/store/reducer.js
src/main/core/Configuration/PlatformDefaults.php
src/main/core/Controller/SearchController.php
src/main/core/Installation/AdditionalInstaller.php
src/main/core/Installation/Updater/Updater130032.php
src/main/core/Resources/config/services/updater.yml
src/main/theme/Resources/modules/administration/appearance/ui/components/main.jsx

[Header] updates widgets configuration format

---

src/main/app/API/Crud.php
src/main/core/API/Crud/User/UserCrud.php
src/main/core/API/Serializer/User/UserSerializer.php
src/main/core/Entity/User.php
src/plugin/saml/Configuration/PlatformDefaults.php
src/plugin/saml/Controller/AuthenticationController.php
src/plugin/saml/Manager/IdpManager.php
src/plugin/saml/Resources/config/services.yml
src/plugin/saml/Resources/config/services/manager.yml
src/plugin/saml/Resources/config/services/security.yml
src/plugin/saml/Security/Authentication/AuthenticationSuccessListener.php
src/plugin/saml/Security/UserCreator.php

[Saml] enhances idp configuration

---

src/plugin/cursus/Entity/Course.php
src/plugin/cursus/Installation/Migrations/pdo_mysql/Version20210910090101.php
src/plugin/cursus/Resources/modules/course/components/about.jsx
src/plugin/cursus/Resources/modules/course/components/details.jsx
src/plugin/cursus/Resources/modules/course/components/form.jsx
src/plugin/cursus/Resources/modules/course/components/list.jsx
src/plugin/cursus/Resources/modules/data/sources/courses.js
src/plugin/cursus/Resources/modules/prop-types.js
src/plugin/cursus/Resources/modules/session/components/form.jsx
src/plugin/cursus/Resources/modules/session/components/list.jsx
src/plugin/cursus/Resources/schemas/course.json
src/plugin/cursus/Resources/schemas/session.json
src/plugin/cursus/Resources/translations/cursus.en.json
src/plugin/cursus/Resources/translations/cursus.fr.json
src/plugin/cursus/Serializer/CourseSerializer.php
src/plugin/cursus/Serializer/SessionSerializer.php

[Trainings] allows to hide sessions

---

src/plugin/saml/Resources/config/services/security.yml
src/plugin/saml/Security/Authentication/AuthenticationSuccessListener.php

[Saml] fixes di

---

src/main/core/Installation/Migrations/pdo_mysql/Version20210908090043.php

[Trainings] fixes migration

---

src/plugin/exo/Resources/modules/quiz/player/components/attempt-end.jsx
src/plugin/path/Resources/modules/resources/path/player/components/end.jsx

fixes home links in embedded resources

---

src/main/authentication/Resources/config/services.yml
src/main/authentication/Resources/config/services/subscriber.yml
src/main/authentication/Subscriber/RefreshTokenSubscriber.php
src/main/core/API/Crud/User/GroupCrud.php
src/main/core/API/Crud/User/RoleCrud.php
src/main/core/API/Crud/User/UserCrud.php
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Event/Security/AbstractRoleEvent.php
src/main/core/Event/Security/AddRoleEvent.php
src/main/core/Event/Security/RemoveRoleEvent.php
src/main/core/Resources/config/services/crud.yml
src/main/log/Subscriber/SecurityLogSubscriber.php

[Security] fixes token refresh on roles changes

---

src/main/core/Manager/Workspace/WorkspaceManager.php
src/main/core/Repository/WorkspaceRepository.php
src/main/core/Security/Voter/WorkspaceVoter.php

[Workspace] fixes accesses

---

src/main/core/Resources/modules/administration/community/parameters/components/parameters-tab.jsx
src/main/core/Resources/translations/platform.fr.json

Orthographe

---

src/plugin/notification/Serializer/NotificationSerializer.php

[Notification] fixes serialization when creator no longer exists

---

src/main/core/Manager/Resource/ResourceEvaluationManager.php

[Evaluation] updates user score when score max changes

---

src/main/core/API/Transfer/Action/Workspace/Archive.php
src/main/core/API/Transfer/Action/Workspace/Unarchive.php
src/main/core/Controller/APINew/Workspace/WorkspaceController.php
src/main/core/Manager/Workspace/WorkspaceManager.php
src/main/core/Resources/config/services/transfer.yml
src/main/core/Resources/samples/workspace/csv/valid/archive/by_code.csv
src/main/core/Resources/samples/workspace/csv/valid/archive/by_id.csv
src/main/core/Resources/samples/workspace/csv/valid/unarchive/by_code.csv
src/main/core/Resources/samples/workspace/csv/valid/unarchive/by_id.csv
src/main/core/Resources/translations/transfer.en.json
src/main/core/Resources/translations/transfer.fr.json

[Transfer] adds ws archive and unarchive actions

---

src/main/core/API/Crud/User/UserCrud.php

[Community] fixes group registration

---

src/main/core/API/Crud/Resource/ResourceNodeCrud.php
src/main/core/API/Crud/WorkspaceCrud.php
src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
src/main/core/Entity/Facet/FieldFacet.php
src/main/core/Listener/Resource/ResourceListener.php
src/main/core/Manager/ResourceManager.php
src/main/core/Resources/config/services/crud.yml
src/plugin/home/Resources/modules/home/widgets/components/tab.jsx
src/plugin/path/Listener/Resource/PathListener.php
src/plugin/path/Resources/config/services/listener.yml
src/plugin/team/Manager/TeamManager.php

[Resource] fixes copy

---

src/main/core/Resources/modules/resource/components/overview.jsx
src/main/evaluation/Resources/translations/evaluation.en.json
src/main/evaluation/Resources/translations/evaluation.fr.json
src/plugin/exo/Manager/Attempt/PaperManager.php
src/plugin/path/Manager/UserProgressionManager.php

fixes resources evaluation

---

src/plugin/cursus/Installation/Migrations/pdo_mysql/Version20211005100000.php

[Trainings] fixes training deletion

---

src/main/evaluation/Controller/WorkspaceEvaluationController.php
src/plugin/analytics/Manager/AnalyticsManager.php

fixed dashboard

---

src/main/installation/Resources/config/services/manager.yml

[Installation] fixes node_modules symlink

---

src/main/core/Security/Voter/AbstractRoleSubjectVoter.php

[Community] fixes registration right check

---

src/plugin/claco-form/Serializer/FieldChoiceCategorySerializer.php

[ClacoForm] fixes categories configuration

---

src/main/dev/Command/RouterDebugCommand.php
src/plugin/open-badge/Controller/API/BadgeClassController.php
src/plugin/open-badge/Resources/config/routing.yml
src/plugin/open-badge/Resources/config/services/controller.yml
src/plugin/open-badge/Resources/modules/tools/badges/badge/components/details.jsx
src/plugin/open-badge/Resources/modules/tools/badges/components/menu.jsx
src/plugin/open-badge/Resources/modules/tools/badges/components/tool.jsx
src/plugin/open-badge/Resources/modules/tools/badges/containers/menu.jsx
src/plugin/open-badge/Resources/modules/tools/badges/containers/tool.jsx

[Badge] adds export for all granted badges

---

src/main/evaluation/Manager/AbstractEvaluationManager.php

[Evaluation] fixes progression

---

src/plugin/cursus/Resources/modules/data/types/course/components/filter.jsx
src/plugin/cursus/Resources/modules/data/types/course/index.js

[Training] adds search component for course data type

---

src/main/core/Resources/modules/tinymce/config.js
src/plugin/cursus/Resources/modules/data/types/course/components/filter.jsx
src/plugin/cursus/Resources/modules/data/types/course/index.js
src/plugin/open-badge/Manager/BadgeManager.php
src/plugin/open-badge/Resources/config/config.yml

merge 13.0 into 13.1

---

src/integration/big-blue-button/Controller/AdministrationController.php
src/integration/big-blue-button/Resources/config/services/controller.yml
src/main/app/Resources/config/services/manager.yml
src/main/core/API/Serializer/ParametersSerializer.php
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Controller/APINew/Platform/ArchiveController.php
src/main/core/Controller/APINew/Workspace/RegistrationController.php
src/main/core/Resources/config/services/controller.yml
src/main/core/Resources/config/services/serializer.yml
src/plugin/analytics/Controller/Workspace/DashboardController.php
src/plugin/announcement/Finder/AnnouncementFinder.php

Avoiding direct dependency to `Finder` will later help to move it into the `Repository`.

replaces Finder by Crud in DI

---

src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Controller/APINew/Workspace/WorkspaceController.php
src/main/core/Resources/config/config.yml
src/main/core/Resources/modules/tools/workspaces/components/menu.jsx
src/main/core/Resources/modules/tools/workspaces/components/tool.jsx
src/main/core/Resources/modules/tools/workspaces/containers/menu.jsx
src/main/core/Resources/modules/tools/workspaces/containers/tool.jsx
src/main/core/Resources/modules/tools/workspaces/store/reducer.js
src/main/core/Resources/modules/workspace/actions/archive.js
src/main/core/Resources/modules/workspace/actions/unarchive.js
src/main/core/Resources/modules/workspace/components/card.jsx
src/main/core/Resources/modules/workspace/modals/about/components/about.jsx
src/main/core/Resources/translations/workspace.en.json
src/main/core/Resources/translations/workspace.fr.json

[Workspace] add tool tab and right to manage archives

---

src/main/core/Manager/Workspace/WorkspaceManager.php
src/main/evaluation/Messenger/AddWorkspaceRequirementsHandler.php

Event `SecurityEvents::ADD_ROLE` was dispatched twice, which breaks subcribers.

[Community] fixes personal ws creation

---

src/main/core/Manager/Workspace/WorkspaceManager.php
src/main/evaluation/Messenger/AddWorkspaceRequirementsHandler.php

[Community] fixes personal ws creation (13.1)

---

src/main/core/Resources/modules/data/sources/resources.js
src/main/core/Resources/modules/resource/components/page.jsx
src/main/core/Resources/modules/resource/modals/about/components/about.jsx
src/main/core/Resources/translations/platform.fr.json

[Resource] fixes translation and redirect after delete

---

src/plugin/cursus/Listener/DataSource/AllCoursesSource.php
src/plugin/cursus/Listener/DataSource/PublicSessionSource.php
src/plugin/cursus/Listener/DataSource/SessionSource.php
src/plugin/cursus/Resources/modules/data/sources/events.js

[Training] fixes data sources

---

src/main/core/Resources/modules/data/sources/resources.js
src/main/core/Resources/modules/resource/components/page.jsx
src/main/core/Resources/modules/resource/modals/about/components/about.jsx
src/main/core/Resources/translations/platform.fr.json
src/plugin/cursus/Listener/DataSource/AllCoursesSource.php
src/plugin/cursus/Listener/DataSource/PublicSessionSource.php
src/plugin/cursus/Listener/DataSource/SessionSource.php
src/plugin/cursus/Resources/modules/data/sources/events.js

merge fixes from 13.0

---

src/main/app/Resources/modules/content/components/rights.jsx

fixes role deletion in objects rights

---

src/main/app/Resources/modules/content/components/rights.jsx

fixes role deletion in objects rights (13.1)

---

src/main/evaluation/Controller/WorkspaceEvaluationController.php

| Bug fix?      |/no
| New feature?  |/no
| BC breaks?    |/no

[Evaluation] adds some user meta in export

---

src/main/core/Installation/Migrations/pdo_mysql/Version20211026053317.php
src/main/core/Installation/Updater/Updater130100.php

[Template] fixes 13.1 upgrade

---

src/plugin/cursus/Crud/EventCrud.php
src/plugin/cursus/Manager/SessionManager.php
src/plugin/cursus/Resources/config/services/crud.yml
src/plugin/cursus/Resources/modules/course/components/participants.jsx

[Training] bug fixes and enhancements

---

src/plugin/cursus/Crud/EventCrud.php
src/plugin/cursus/Manager/SessionManager.php
src/plugin/cursus/Resources/config/services/crud.yml
src/plugin/cursus/Resources/modules/course/components/participants.jsx

[Training] bug fixes and enhancements (13.1)

---

src/main/core/Repository/WorkspaceRepository.php
src/plugin/agenda/Finder/AbstractEventFinder.php

[Workspace] fixes searches

---

src/main/core/Manager/MailManager.php
src/main/core/Resources/modules/administration/template/components/tool.jsx
src/main/core/Resources/modules/administration/template/containers/tool.jsx
src/main/core/Resources/views/template/email_layout.en.html.twig
src/main/core/Resources/views/template/email_layout.fr.html.twig

[Template] fixes renaming

---

src/main/app/Manager/PdfManager.php
src/main/app/Resources/config/services/manager.yml
src/main/app/Resources/views/pdf.html.twig
src/main/core/Controller/APINew/Resource/Types/TextController.php
src/main/core/Resources/config/services/controller.yml
src/plugin/claco-form/Controller/ClacoFormController.php
src/plugin/claco-form/Resources/config/services/controller.yml
src/plugin/claco-form/Resources/views/claco_form/entry.html.twig
src/plugin/cursus/Controller/CourseController.php
src/plugin/cursus/Controller/EventController.php
src/plugin/cursus/Controller/EventPresenceController.php
src/plugin/cursus/Controller/SessionController.php
src/plugin/cursus/Resources/config/services/controller.yml
src/plugin/lesson/Controller/ChapterController.php
src/plugin/lesson/Controller/LessonController.php
src/plugin/lesson/Resources/config/services/controller.yml
src/plugin/lesson/Resources/views/lesson/open.pdf.twig
src/plugin/open-badge/Controller/API/AssertionController.php
src/plugin/open-badge/Resources/config/services/controller.yml

[PDF] fixes external resources urls

---

src/main/core/Resources/less/layout/list/index.less
src/plugin/claco-form/Resources/modules/data/sources/entries.js
src/plugin/claco-form/Resources/modules/resources/claco-form/editor/components/editor.jsx

[ClacoForm] fixes custom fields labels and search

---

src/main/core/Listener/PlatformListener.php
src/main/core/Resources/config/services/listener.yml
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json

fixes translations in changelog connection message

---

src/main/core/Listener/PlatformListener.php
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json

[Changelog] displays end date of the connection message

---

src/plugin/open-badge/Finder/AssertionFinder.php
src/plugin/open-badge/Resources/modules/tools/badges/badge/components/details.jsx

[Badge] sorts badge assertions by user last name

---

src/main/core/Installation/Migrations/pdo_mysql/Version20211213100000.php
src/main/core/Resources/modules/workspace/modals/about/store/actions.js
src/plugin/claco-form/Finder/EntryFinder.php
src/plugin/claco-form/Resources/config/services/finder.yml

debug 13.1.2

---

src/main/core/Installation/Migrations/pdo_mysql/Version20211213100000.php

[Facet] fixes string values escaping

---

src/main/core/Resources/modules/tinymce/components/tinymce.jsx

[Home] fixes tinymce in simple widget parameters

---

README.md

[Documentation] fixes technical guide url

---

src/plugin/team/Controller/API/TeamController.php
src/plugin/team/Repository/TeamRepository.php
src/plugin/team/Resources/config/services/voter.yml
src/plugin/team/Security/Voter/RoleVoter.php
src/plugin/team/Security/Voter/TeamVoter.php

Gives open right on team roles to users who can open the linked team (to be able to list team users).

[Team] fixes access rights

---

src/plugin/drop-zone/Resources/modules/resources/dropzone/player/components/my-drop.jsx
src/plugin/drop-zone/Resources/translations/dropzone.fr.json

[Dropzone] renames submit button

---

src/main/core/Controller/APINew/Platform/ParametersController.php
src/main/core/Controller/APINew/User/CommunityController.php
src/main/core/Resources/config/services/controller.yml
src/main/core/Resources/modules/administration/community/parameters/components/parameters-tab.jsx

fixes platform parameters access rights

---

src/main/core/API/Finder/User/UserFinder.php

disallows authentication props in user finder

---

src/plugin/claco-form/Finder/EntryFinder.php

[ClacoForm] fixes entry search by user

---

src/main/core/API/Validator/UserValidator.php
src/main/core/Entity/Role.php
src/main/core/Resources/config/services/validator.yml

[Community] validates user roles

---

src/main/core/Resources/schemas/resource/types/directory.json

[Directory] fixes schema

---

src/main/core/Resources/modules/resources/directory/store/reducer.js
src/plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry-form.jsx
src/plugin/claco-form/Resources/modules/resources/claco-form/template.js
src/plugin/cursus/Resources/modules/course/components/sessions.jsx
src/plugin/drop-zone/Resources/modules/resources/dropzone/components/documents.jsx
src/plugin/drop-zone/Resources/modules/resources/dropzone/player/components/my-drop.jsx
src/plugin/message/Resources/config/services/voter.yml
src/plugin/message/Security/Voter/ContactVoter.php

debug 13.1.3

---

src/main/core/API/Serializer/ParametersSerializer.php
src/main/core/Installation/Migrations/pdo_mysql/Version20211002092659.php
src/main/core/Listener/Doctrine/TranslatableListener.php

[Parameters] fixes tos

---

src/main/core/Resources/modules/workspace/components/form.jsx

[Workspace] fixes creation from model

---

src/main/core/Resources/modules/tinymce/components/tinymce.jsx

[TinyMce] fixes editor loading

---

src/main/core/Resources/modules/data/sources/resources.js
src/main/core/Resources/translations/resource.en.json
src/main/core/Resources/translations/resource.fr.json

[Resource] adds required prop in data source

---

src/plugin/open-badge/Listener/Rules/ResourceEvaluationListener.php

[Badge] fixes resource completion rule

---

src/main/evaluation/Controller/ResourceUserEvaluationController.php
src/main/evaluation/Resources/config/services/controller.yml
src/main/evaluation/Resources/modules/analytics/resource/evaluation/components/dashboard.jsx
src/main/evaluation/Resources/modules/analytics/resource/evaluation/containers/dashboard.jsx
src/main/evaluation/Resources/modules/analytics/resource/evaluation/index.js
src/main/evaluation/Resources/modules/analytics/resource/evaluation/store/index.js
src/main/evaluation/Resources/modules/analytics/resource/evaluation/store/reducer.js
src/main/evaluation/Resources/modules/analytics/resource/evaluation/store/selectors.js
src/main/evaluation/Resources/modules/data/sources/resource-attempts.js
src/main/evaluation/Resources/modules/data/sources/resource-evaluations.js
src/main/evaluation/Resources/modules/data/sources/workspace-evaluations.js
src/main/evaluation/Resources/modules/modals/resource-evaluations/components/modal.jsx
src/main/evaluation/Resources/modules/plugin.js
src/main/evaluation/Resources/modules/tools/evaluation/components/users.jsx
src/plugin/analytics/Resources/modules/resource/utils.js
src/plugin/analytics/Resources/modules/tools/dashboard/path/modals/participants/components/modal.jsx
src/plugin/analytics/Resources/translations/actions.en.json
src/plugin/analytics/Resources/translations/actions.fr.json
src/plugin/path/Controller/PathController.php
src/plugin/path/Controller/PathTrackingController.php
src/plugin/path/Resources/config/services/controller.yml
src/plugin/path/Resources/modules/analytics/resource/progression/components/progression.jsx
src/plugin/path/Resources/modules/analytics/resource/progression/containers/progression.jsx
src/plugin/path/Resources/translations/actions.en.json
src/plugin/path/Resources/translations/actions.fr.json

[Resource] displays evaluations in resource dashboard

---

src/main/core/API/Transfer/Action/User/Create.php
src/main/core/API/Transfer/Action/User/Update.php

[Transfer] fixes user create and update

---

src/plugin/saml/Configuration/PlatformDefaults.php
src/plugin/saml/Manager/IdpManager.php
src/plugin/saml/Security/Authentication/AuthenticationSuccessListener.php

[Saml] adds conditions for group and organization registration

---

src/main/app/Resources/modules/api/fetch/fetch.js
src/main/core/Controller/ResourceController.php
src/main/core/Controller/WorkspaceController.php
src/main/core/Manager/Resource/ResourceRestrictionsManager.php
src/main/core/Manager/Workspace/WorkspaceRestrictionsManager.php
src/main/core/Resources/config/services/manager.yml
src/main/core/Resources/modules/resource/components/restrictions.jsx
src/main/core/Resources/modules/resource/containers/page.jsx
src/main/core/Resources/modules/resource/store/actions.js
src/main/core/Resources/modules/resource/store/reducer.js
src/main/core/Resources/modules/workspace/components/restrictions.jsx
src/main/core/Resources/modules/workspace/store/actions.js
src/main/core/Resources/modules/workspace/store/reducer.js
src/main/core/Resources/modules/workspace/store/selectors.js
src/main/core/Resources/translations/resource.en.json
src/main/core/Resources/translations/resource.fr.json
src/main/core/Resources/translations/workspace.en.json
src/main/core/Resources/translations/workspace.fr.json

updates workspace and resource restrictions page

---

src/main/core/Controller/FileController.php

[File] fixes filename

---

src/plugin/pdf-player/Controller/UserEvaluationController.php

[PDF] fixes progression

---

src/plugin/open-badge/Controller/API/AssertionController.php
src/plugin/open-badge/Finder/AssertionFinder.php
src/plugin/open-badge/Finder/BadgeClassFinder.php
src/plugin/open-badge/Resources/config/services/finder.yml

[Badge] fixes assertions rights

---

src/main/core/API/Validator/UserValidator.php
src/main/core/Entity/Organization/Organization.php
src/main/core/Repository/User/OrganizationRepository.php
src/main/core/Resources/config/services/validator.yml
src/main/core/Security/Voter/AbstractRoleSubjectVoter.php
src/main/core/Security/Voter/GroupVoter.php
src/main/core/Security/Voter/UserVoter.php

[Community] fixes #2018

---

src/plugin/cursus/Controller/CourseController.php
src/plugin/cursus/Controller/EventController.php
src/plugin/cursus/Controller/SessionController.php
src/plugin/cursus/Finder/Registration/CourseUserFinder.php
src/plugin/cursus/Finder/Registration/EventUserFinder.php
src/plugin/cursus/Finder/Registration/SessionUserFinder.php
src/plugin/cursus/Resources/modules/course/components/details.jsx
src/plugin/cursus/Resources/modules/course/components/main.jsx
src/plugin/cursus/Resources/modules/course/containers/main.jsx
src/plugin/cursus/Resources/modules/event/components/details.jsx
src/plugin/cursus/Resources/modules/event/containers/details.jsx
src/plugin/cursus/Resources/translations/cursus.en.json

[Trainings] filters participants by organization

---

src/main/core/API/Serializer/Platform/ClientSerializer.php
src/main/core/API/Validator/UserValidator.php
src/main/core/Configuration/PlatformDefaults.php
src/main/core/Manager/UserManager.php
src/main/core/Resources/config/services/serializer.yml
src/main/core/Resources/modules/administration/community/user/components/users.jsx

[Community] fixes nb users restriction

---

src/main/core/API/Validator/PublicFileValidator.php
src/main/core/Resources/config/services/controller.yml

adds basic file validation

---

src/main/log/Controller/FunctionalLogController.php
src/main/log/Controller/MessageLogController.php
src/main/log/Controller/SecurityLogController.php

[Log] fixes api rights

---

src/plugin/saml/Manager/IdpManager.php
src/plugin/saml/Security/Authentication/AuthenticationSuccessListener.php

[Saml] enhances conditional registration to groups and organization

---

src/main/core/Manager/FileManager.php

disable storage restrictions

---

src/main/evaluation/Resources/modules/tools/evaluation/store/reducer.js

[Evaluation] reloads tool data on open

---

src/plugin/claco-form/Controller/API/CategoryController.php
src/plugin/claco-form/Controller/API/ClacoFormController.php
src/plugin/claco-form/Finder/EntryFinder.php
src/plugin/claco-form/Manager/CategoryManager.php
src/plugin/claco-form/Manager/ClacoFormManager.php
src/plugin/claco-form/Messenger/AssignCategoryHandler.php
src/plugin/claco-form/Messenger/Message/AssignCategory.php
src/plugin/claco-form/Resources/config/services.yml
src/plugin/claco-form/Resources/config/services/controller.yml
src/plugin/claco-form/Resources/config/services/manager.yml
src/plugin/claco-form/Resources/config/services/messenger.yml
src/plugin/claco-form/Resources/config/services/subscriber.yml
src/plugin/claco-form/Resources/modules/modals/category/components/form.jsx
src/plugin/claco-form/Resources/modules/resources/claco-form/editor/components/editor.jsx
src/plugin/claco-form/Resources/modules/resources/claco-form/editor/store/actions.js
src/plugin/claco-form/Subscriber/EntrySubscriber.php

[ClacoForm] fixes category management

---

src/plugin/cursus/Resources/modules/event/components/card.jsx

Replaces https://github.com/claroline/Claroline/pull/1813.

[Training] adds css classes to event cards

---

src/main/core/Resources/modules/resources/file/player/components/overview.jsx
src/main/core/Resources/translations/file.en.json
src/main/core/Resources/translations/file.fr.json

[File] displays help message for auto download

---

src/main/core/Command/UpdateRichTextCommand.php

updates html content replacer

---

src/main/core/Controller/APINew/User/ProfileController.php
src/main/core/Resources/modules/administration/community/profile/components/facet.jsx
src/main/core/Resources/modules/user/profile/editor/components/facet.jsx
src/main/core/Resources/modules/user/profile/utils.js

[Community] fixes profile edition

---

src/integration/big-blue-button/Manager/BBBManager.php
src/main/core/Command/User/DeleteDisabledCommand.php
src/main/core/Command/Workspace/DeleteArchivedCommand.php
src/main/core/Event/Log/LogResourceDeleteEvent.php
src/main/core/Event/Log/LogWorkspaceDeleteEvent.php
src/main/core/Listener/Resource/Types/DirectoryListener.php
src/main/core/Resources/config/services/command.yml
src/main/core/Resources/modules/administration/community/role/store/actions.js
src/main/core/Resources/modules/administration/template/components/form.jsx
src/main/core/Resources/modules/tinymce/config.js
src/main/core/Resources/modules/tools/workspaces/components/tool.jsx

debug 13.3.0

---

src/main/transfer/Resources/modules/tools/transfer/export/components/list.jsx

[Transfer] fixes export deletion

---

src/main/core/Tests/Database/Repository/WorkspaceRepositoryTest.php
src/main/migration/Migrations/ConditionalMigrationTrait.php
src/plugin/favourite/Installation/Migrations/pdo_mysql/Version20220314092857.php
src/plugin/wiki/Entity/Section.php
src/plugin/wiki/Installation/Migrations/pdo_mysql/Version20220316131828.php

[Favourite] fixes migration

---

src/main/app/Resources/modules/layout/sections/account/components/main.jsx
src/plugin/open-badge/Resources/modules/account/badges/components/main.jsx
src/plugin/open-badge/Resources/modules/account/badges/containers/main.jsx
src/plugin/open-badge/Resources/modules/account/badges/index.js
src/plugin/open-badge/Resources/modules/account/badges/store/index.js
src/plugin/open-badge/Resources/modules/account/badges/store/reducer.js
src/plugin/open-badge/Resources/modules/account/badges/store/selectors.js
src/plugin/open-badge/Resources/modules/plugin.js
src/plugin/open-badge/Resources/modules/tools/badges/assertion/components/list.jsx
src/plugin/open-badge/Resources/modules/tools/badges/store/reducer.js

[Account] adds badges tab

---

src/main/core/Configuration/PlatformDefaults.php
src/main/core/Installation/ClarolineCoreInstaller.php
src/main/core/Installation/Updater/Updater130303.php
src/main/core/Resources/config/services/updater.yml

disables async messenger by default

---

package.json
src/main/core/Configuration/PlatformDefaults.php
src/main/core/Installation/ClarolineCoreInstaller.php
src/main/core/Installation/Updater/Updater130303.php
src/main/core/Resources/config/services/updater.yml

Merge 13.3

---

src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Resources/config/services/serializer.yml
src/main/core/Resources/modules/data/sources/workspaces.js
src/plugin/tag/Resources/modules/modals/object-tags/components/modal.jsx
src/plugin/tag/Resources/modules/modals/object-tags/containers/modal.jsx

[Workspace] displays tags in lists

---

src/main/core/Entity/AbstractMessage.php
src/plugin/announcement/Entity/Announcement.php
src/plugin/announcement/Installation/Migrations/pdo_mysql/Version20220321155503.php
src/plugin/blog/Entity/Comment.php
src/plugin/blog/Installation/Migrations/pdo_mysql/Version20220321155724.php
src/plugin/claco-form/Entity/Entry.php
src/plugin/claco-form/Installation/Migrations/pdo_mysql/Version20220321155807.php
src/plugin/forum/Entity/Subject.php
src/plugin/forum/Installation/Migrations/pdo_mysql/Version20220321155428.php
src/plugin/scorm/Entity/ScoTracking.php
src/plugin/scorm/Installation/Migrations/pdo_mysql/Version20220321160359.php

[Community] fixes relations management on user delete

---

src/plugin/forum/Event/LogSubjectEvent.php

[Forum] fixes logs

---

src/main/transfer/Transfer/Adapter/CsvAdapter.php

Any `;` or `\n` inside column values breaks the column mapping.

[Transfer] uses col enclosure to allow special chars

---

src/main/app/API/Utils/ArrayUtils.php
src/main/log/Subscriber/Security/AuthenticationLogSubscriber.php
src/main/transfer/Manager/TransferManager.php
src/main/transfer/Transfer/Adapter/AdapterInterface.php
src/main/transfer/Transfer/Adapter/CsvAdapter.php
src/main/transfer/Transfer/Adapter/JsonAdapter.php
src/main/transfer/Transfer/ExportProvider.php

Large exports kill the messenger consumer.

[Transfer] optimizes export

---

src/main/core/Controller/APINew/User/ProfileController.php
src/main/core/Resources/modules/administration/community/profile/components/facet.jsx
src/main/core/Resources/modules/user/profile/editor/components/facet.jsx
src/main/core/Resources/modules/user/profile/utils.js

Missing bugfix from the 13.2 branch.

[Account] fixes profile edition

---

src/plugin/saml/Manager/IdpManager.php

[Saml] allows condition on array values

---

src/plugin/open-badge/Finder/AssertionFinder.php

[Badge] fixes assertions export for non admin

---

src/plugin/announcement/Resources/modules/resources/announcement/modals/sending/containers/modal.jsx

[Announcement] fixes sending when no cron

---

src/main/app/Resources/modules/buttons/url/components/button.jsx
src/plugin/saml/Configuration/PlatformDefaults.php
src/plugin/saml/Listener/Platform/SamlSsoListener.php
src/plugin/saml/Resources/modules/sso/saml/components/button.jsx

[Saml] adds confirm before redirecting to idp

---

src/main/app/Entity/Identifier/Code.php
src/main/core/API/Serializer/Tool/OrderedToolSerializer.php
src/main/core/Entity/Tool/OrderedTool.php
src/main/core/Installation/Migrations/pdo_mysql/Version20220317084050.php
src/main/core/Manager/Workspace/WorkspaceManager.php
src/main/core/Resources/modules/administration/template/components/page.jsx
src/main/core/Resources/modules/administration/template/containers/page.jsx
src/main/core/Resources/modules/tool/components/page.jsx
src/main/core/Resources/modules/tool/containers/page.jsx
src/main/core/Resources/modules/tool/modals/parameters/components/modal.jsx
src/main/core/Resources/modules/tool/prop-types.js
src/main/core/Resources/modules/tool/store/actions.js
src/main/core/Resources/modules/tool/store/reducer.js
src/main/core/Resources/modules/tool/store/selectors.js
src/main/core/Resources/modules/tools/locations/location/components/page.jsx
src/main/core/Resources/modules/tools/locations/location/containers/page.jsx
src/main/core/Resources/modules/tools/locations/material/components/page.jsx
src/main/core/Resources/modules/tools/locations/material/containers/page.jsx
src/main/core/Resources/modules/tools/locations/room/components/page.jsx
src/main/core/Resources/modules/tools/locations/room/containers/page.jsx
src/plugin/agenda/Resources/modules/event/components/page.jsx
src/plugin/agenda/Resources/modules/event/containers/page.jsx
src/plugin/cursus/Resources/modules/course/components/page.jsx
src/plugin/cursus/Resources/modules/event/components/page.jsx
src/plugin/cursus/Resources/modules/tools/events/components/details.jsx
src/plugin/cursus/Resources/modules/tools/events/containers/details.jsx

allows to open tools in fullscreen by default

---

src/plugin/open-badge/Entity/BadgeClass.php
src/plugin/open-badge/Installation/DataFixtures/Template/BadgeGrantedData.php
src/plugin/open-badge/Installation/Migrations/pdo_mysql/Version20220330070412.php
src/plugin/open-badge/Manager/AssertionManager.php
src/plugin/open-badge/Manager/BadgeManager.php
src/plugin/open-badge/Resources/config/config.yml
src/plugin/open-badge/Resources/config/services/manager.yml
src/plugin/open-badge/Resources/modules/tools/badges/badge/components/form.jsx
src/plugin/open-badge/Resources/translations/badge.en.json
src/plugin/open-badge/Resources/translations/badge.fr.json
src/plugin/open-badge/Resources/translations/template.en.json
src/plugin/open-badge/Resources/translations/template.fr.json
src/plugin/open-badge/Resources/views/template/badge_granted.en.html.twig
src/plugin/open-badge/Resources/views/template/badge_granted.fr.html.twig
src/plugin/open-badge/Serializer/BadgeClassSerializer.php

[Badge] adds notification on badge awarding

---

src/plugin/open-badge/Controller/API/BadgeClassController.php
src/plugin/open-badge/Finder/BadgeClassFinder.php
src/plugin/open-badge/Listener/DataSource/BadgesSource.php
src/plugin/open-badge/Resources/config/services/controller.yml
src/plugin/open-badge/Resources/config/services/listener.yml

[Badge] filters list by organizations

---

src/main/core/Controller/APINew/User/UserController.php
src/main/core/Listener/DataSource/UserSource.php
src/main/core/Resources/config/services/listener.yml

[Community] fixes users source visibility

---

src/main/app/API/Finder/AbstractFinder.php
src/main/app/Resources/modules/api/fetch/fetch.js
src/main/app/Resources/modules/api/prop-types.js
src/main/app/Resources/modules/security/store/actions.js
src/main/app/Resources/translations/security.fr.json
src/main/core/Installation/DataFixtures/Template/UserDisabledData.php
src/main/core/Manager/MailManager.php
src/main/core/Resources/config/config.yml
src/main/core/Resources/views/template/user_disabled.en.html.twig
src/main/core/Resources/views/template/user_disabled.fr.html.twig

- Display correct error message when a disabled user try to login.
- Send a "User disabled" mail instead of the "Forgot password" to disabled users.

[Community] enhances disabled users management

---

src/plugin/home/Resources/modules/tools/home/player/components/tab.jsx

[Home] fixes tab restriction by code

---

changelogs/changelog-13.4.en.md
changelogs/changelog-13.4.fr.md

Changelog 13.4

---

src/plugin/claco-form/Resources/modules/resources/claco-form/editor/components/parameters.jsx
src/plugin/claco-form/Resources/modules/resources/claco-form/store/selectors.js

[ClacoForm] fixes fields order parameter

---

src/plugin/open-badge/Manager/BadgeManager.php

[Badges] fixes certificate if no organization

---

src/plugin/saml/Listener/Platform/SamlSsoListener.php
src/plugin/saml/Resources/modules/sso/saml/components/button.jsx

[Saml] fixes sso button rendering

---

src/main/app/Manager/TermsOfServiceManager.php

[Community] fixes registration terms of service

---

src/main/core/Resources/modules/user/components/list.jsx

[Community] fixes user search by email

---

src/main/app/Entity/Meta/Creator.php
src/main/core/Manager/UserManager.php
src/main/transfer/Transfer/ImportProvider.php

[Transfer] fixes messenger task

---

src/main/core/Transfer/Importer/User/Create.php
src/main/transfer/Messenger/ExecuteImportHandler.php

[Transfer] fixes import

---

src/main/core/API/Serializer/Template/TemplateSerializer.php

[Template] fixes empty templates edition

---

src/main/app/API/Crud.php
src/main/core/Manager/Workspace/TransferManager.php
src/main/core/Resources/modules/tools/workspaces/components/tool.jsx

[Workspace] fixes creation

---

src/plugin/open-badge/Manager/AssertionManager.php

[Badge] fixes multiple notif on attribution

---

src/main/app/API/Options.php
src/main/app/API/SchemaProvider.php
src/main/app/API/Serializer/SerializerInterface.php
src/main/app/API/ValidatorProvider.php
src/main/core/API/Serializer/User/UserSerializer.php
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Resources/samples/workspace/json/valid/create/full.json
src/main/core/Tests/NewAPI/FinderProviderTest.php
src/main/core/Tests/NewAPI/SerializerProviderTest.php
src/main/transfer/Transfer/ActionInterface.php
src/main/transfer/Transfer/Adapter/AdapterInterface.php
src/main/transfer/Transfer/Adapter/CsvAdapter.php
src/main/transfer/Transfer/Adapter/JsonAdapter.php
src/main/transfer/Transfer/ExportProvider.php
src/main/transfer/Transfer/Exporter/AbstractExporter.php
src/main/transfer/Transfer/Exporter/AbstractListExporter.php
src/main/transfer/Transfer/Exporter/ExporterInterface.php
src/main/transfer/Transfer/Importer/ImporterInterface.php
src/plugin/blog/Serializer/PostSerializer.php
src/plugin/message/Serializer/MessageSerializer.php

[Transfer] batch export for performances

---

src/main/core/Transfer/Importer/User/Update.php

[Transfer] fixes users update

---

src/main/app/API/FinderProvider.php
src/main/app/API/Options.php
src/main/app/API/SchemaProvider.php
src/main/app/API/Serializer/SerializerInterface.php
src/main/app/API/Serializer/SerializerTrait.php
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Controller/APINew/SwaggerController.php
src/main/core/Tests/NewAPI/SerializerProviderTest.php
src/main/transfer/Resources/config/services/transfer.yml
src/main/transfer/Transfer/Adapter/CsvAdapter.php
src/main/transfer/Transfer/Exporter/AbstractListExporter.php

[Transfer] enhances performances

---

src/main/log/Subscriber/Security/RoleLogSubscriber.php

[Community] fixes self registration

---

src/main/app/API/FinderProvider.php
src/main/app/API/Options.php
src/main/app/API/SchemaProvider.php
src/main/app/API/Serializer/SerializerInterface.php
src/main/app/API/Serializer/SerializerTrait.php
src/main/app/API/ValidatorProvider.php
src/main/core/API/Serializer/User/UserSerializer.php
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Controller/APINew/SwaggerController.php
src/main/core/Resources/samples/workspace/json/valid/create/full.json
src/main/core/Tests/NewAPI/FinderProviderTest.php
src/main/core/Tests/NewAPI/SerializerProviderTest.php
src/main/core/Transfer/Importer/User/Update.php
src/main/log/Subscriber/Security/RoleLogSubscriber.php
src/main/transfer/Resources/config/services/transfer.yml
src/main/transfer/Transfer/ActionInterface.php
src/main/transfer/Transfer/Adapter/AdapterInterface.php
src/main/transfer/Transfer/Adapter/CsvAdapter.php
src/main/transfer/Transfer/Adapter/JsonAdapter.php
src/main/transfer/Transfer/ExportProvider.php
src/main/transfer/Transfer/Exporter/AbstractExporter.php
src/main/transfer/Transfer/Exporter/AbstractListExporter.php
src/main/transfer/Transfer/Exporter/ExporterInterface.php
src/main/transfer/Transfer/Importer/ImporterInterface.php
src/plugin/blog/Serializer/PostSerializer.php
src/plugin/message/Serializer/MessageSerializer.php

merge 13.4 into 13.5

---

src/main/core/API/Serializer/Template/TemplateSerializer.php

[Template] fixes content not serialized

---

src/main/app/Resources/modules/layout/sections/home/constants.js
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json

[Parameters] enhances translations

---

src/main/core/Installation/ClarolineCoreInstaller.php
src/main/core/Installation/Updater/Updater130406.php
src/main/core/Resources/config/services/updater.yml
src/main/installation/Additional/AdditionalInstaller.php

[Workspace] initializes missing manager role

---

src/main/core/Resources/config/services/updater.yml

[Core] fixes updater service

---

src/main/community/Resources/config/services.yml
src/main/core/Resources/modules/tool/constants.js
src/plugin/cursus/Resources/modules/home/catalog/index.js
src/plugin/link/Entity/Home/ToolShortcutTab.php
src/plugin/link/Installation/Migrations/pdo_mysql/Version20220516065911.php
src/plugin/link/Resources/config/services.yml
src/plugin/link/Resources/config/services/listener.yml
src/plugin/link/Resources/config/services/serializer.yml
src/plugin/link/Resources/modules/home/tool-shortcut/components/parameters.jsx
src/plugin/link/Resources/modules/home/tool-shortcut/components/tab.jsx
src/plugin/link/Resources/modules/home/tool-shortcut/containers/parameters.jsx
src/plugin/link/Resources/modules/home/tool-shortcut/index.js
src/plugin/link/Resources/modules/plugin.js
src/plugin/link/Resources/translations/home.en.json
src/plugin/link/Resources/translations/home.fr.json
src/plugin/link/Serializer/Home/ToolShortcutSerializer.php
src/plugin/url/Resources/config/config.yml
src/plugin/url/Resources/modules/plugin.js

[Home] adds tool shortcut tab

---

src/main/community/Security/Voter/OrganizationVoter.php

[Community] fixes organization rights (13.5)

---

src/main/core/Security/Voter/OrganizationVoter.php

[Community] fixes organization rights

---

src/plugin/wiki/Controller/SectionController.php
src/plugin/wiki/Manager/SectionManager.php
src/plugin/wiki/Resources/modules/resources/wiki/player/store/actions.js

[Wiki] fixes set visibility feature

---

src/plugin/wiki/Controller/SectionController.php
src/plugin/wiki/Manager/SectionManager.php
src/plugin/wiki/Resources/modules/resources/wiki/player/store/actions.js

[Wiki] fixes set visibility feature (13.5)

---

src/plugin/analytics/Resources/config/services/updater.yml

[Analytics] fixes updater declaration

---

src/main/core/API/Finder/Tool/ToolFinder.php
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Resources/modules/workspace/prop-types.js
src/main/core/Subscriber/Tool/ResourcesSubscriber.php

[[Workspace] fixes copy of the opening config](https://github.com/claroline/Claroline/commit/de9c11c3155e4a85e5fd863370e9c79dd7568226) also fixes the copy of quizzes (questions were not copied).

Debug 13.5

---

src/plugin/open-badge/Transfer/Exporter/AssertionListExporter.php

[Badge] fixes assertion export schema

---

src/main/transfer/Resources/modules/tools/transfer/components/details.jsx
src/main/transfer/Resources/modules/tools/transfer/export/components/details.jsx
src/main/transfer/Resources/modules/tools/transfer/export/components/form.jsx
src/main/transfer/Resources/modules/tools/transfer/export/components/list.jsx
src/main/transfer/Resources/modules/tools/transfer/export/containers/details.jsx
src/main/transfer/Resources/modules/tools/transfer/export/containers/form.jsx
src/main/transfer/Resources/modules/tools/transfer/import/components/details.jsx
src/main/transfer/Resources/modules/tools/transfer/import/components/explanation.jsx
src/main/transfer/Resources/modules/tools/transfer/import/components/form.jsx
src/main/transfer/Resources/modules/tools/transfer/import/components/list.jsx
src/main/transfer/Resources/modules/tools/transfer/import/containers/details.jsx
src/main/transfer/Resources/modules/tools/transfer/import/containers/form.jsx
src/main/transfer/Resources/modules/tools/transfer/index.js

[Transfer] allows to edit import/export

---

src/main/community/Finder/UserFinder.php
src/main/core/Manager/Tool/ToolManager.php
src/main/core/Resources/config/services/exporter.yml
src/main/core/Resources/modules/workspace/components/menu.jsx
src/main/core/Resources/modules/workspace/constants.js
src/main/core/Resources/translations/transfer.en.json
src/main/core/Resources/translations/transfer.fr.json
src/main/core/Transfer/Exporter/Workspace/ListManagersExporter.php
src/main/evaluation/Finder/WorkspaceEvaluationFinder.php
src/main/evaluation/Transfer/Exporter/AbstractEvaluationListExporter.php
src/main/transfer/Resources/modules/tools/transfer/export/components/details.jsx
src/plugin/link/Resources/modules/home/tool-shortcut/containers/parameters.jsx

enhances transfer

---

src/main/app/Resources/modules/api/store/actions.js
src/main/app/Resources/modules/data/types/file/components/input.jsx
src/main/app/Resources/modules/data/types/image/components/input.jsx
src/main/core/Controller/APINew/FileController.php
src/main/core/Resources/modules/administration/parameters/modals/slide/components/modal.jsx
src/main/core/Resources/modules/layout/form/components/field/file.jsx
src/main/core/Resources/modules/resource/components/form.jsx
src/main/core/Resources/modules/tool/modals/parameters/components/modal.jsx
src/main/core/Resources/modules/user/profile/utils.js
src/main/core/Resources/translations/validators.en.json
src/main/core/Resources/translations/validators.fr.json
src/plugin/announcement/Resources/modules/resources/announcement/components/announce-form.jsx
src/plugin/competency/Resources/modules/administration/competency/framework/components/framework-import.jsx
src/plugin/forum/Resources/modules/resources/forum/player/components/subject-form.jsx
src/plugin/home/Resources/modules/tools/home/editor/components/form.jsx
src/plugin/lesson/Resources/modules/resources/lesson/components/chapter-form.jsx
src/plugin/path/Resources/modules/resources/path/editor/components/step.jsx

This allows us to check the uploaded file is a correct image.

adds api endpoint for image uploads

---

changelogs/changelog-13.5.en.md
changelogs/changelog-13.5.fr.md
src/main/evaluation/Controller/WorkspaceEvaluationController.php
src/main/evaluation/Resources/config/config.yml
src/main/evaluation/Resources/modules/analytics/resource/evaluation/components/dashboard.jsx
src/main/evaluation/Resources/modules/tools/evaluation/components/menu.jsx
src/main/evaluation/Resources/modules/tools/evaluation/components/tool.jsx
src/main/evaluation/Resources/modules/tools/evaluation/components/user.jsx
src/main/evaluation/Resources/modules/tools/evaluation/components/users.jsx
src/main/evaluation/Resources/modules/tools/evaluation/containers/menu.jsx
src/main/evaluation/Resources/modules/tools/evaluation/containers/tool.jsx
src/main/evaluation/Resources/translations/actions.en.json
src/main/evaluation/Resources/translations/actions.fr.json
src/main/evaluation/Security/Voter/AbstractEvaluationVoter.php
src/main/evaluation/Security/Voter/ResourceUserEvaluationVoter.php
src/main/evaluation/Security/Voter/WorkspaceEvaluationVoter.php

enhances evaluations

---

changelogs/changelog-13.5.en.md
changelogs/changelog-13.5.fr.md
src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
src/main/core/Installation/Migrations/pdo_mysql/Version20220614112516.php
src/main/core/Resources/modules/resource/components/form.jsx
src/main/core/Resources/modules/resource/components/overview.jsx
src/main/core/Resources/modules/resource/modals/about/components/about.jsx
src/main/core/Resources/modules/workspace/components/card.jsx
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.es.json
src/main/core/Resources/translations/platform.fr.json
src/main/evaluation/Entity/Evaluated.php
src/main/evaluation/Resources/translations/platform.en.json
src/main/evaluation/Resources/translations/platform.fr.json
src/plugin/drop-zone/Resources/modules/resources/dropzone/overview/components/overview.jsx
src/plugin/drop-zone/Resources/modules/resources/dropzone/overview/containers/overview.jsx
src/plugin/exo/Resources/modules/resources/quiz/overview/components/main.jsx
src/plugin/exo/Resources/modules/resources/quiz/overview/containers/main.jsx
src/plugin/lesson/Resources/modules/resources/lesson/components/overview.jsx
src/plugin/lesson/Resources/modules/resources/lesson/containers/overview.jsx
src/plugin/path/Resources/modules/resources/path/components/overview.jsx

[Resource] adds estimated duration meta

---

src/plugin/path/Resources/modules/resources/path/containers/overview.jsx

[Path] fixes overview

---

src/plugin/claco-form/Resources/views/claco_form/entry.html.twig

[ClacoForm] fixes pdf export

---

src/plugin/tag/Installation/Migrations/pdo_mysql/Version20220425084528.php

[Tags] fixes migrations

---

src/main/app/Resources/modules/api/store/actions.js
src/main/app/Resources/modules/data/types/file/components/input.jsx
src/main/app/Resources/modules/data/types/image/components/input.jsx
src/main/core/Resources/modules/layout/form/components/field/file.jsx
src/main/core/Subscriber/Tool/ResourcesSubscriber.php

debug 13.5.1

---

src/plugin/tag/Installation/Migrations/pdo_mysql/Version20220425084528.php

[Tag] fixes migrations (again)

---

.github/workflows/release_patch.yml

[CI] fixes patch release action

---

src/main/app/Resources/config/suggested/monolog_dev.yml
src/main/app/Resources/config/suggested/sensio_framework_extra.yml

integrates sentry

---

src/plugin/exo/Entity/ItemType/GridQuestion.php
src/plugin/exo/Installation/Migrations/pdo_mysql/Version20220624075933.php

This causes MySQL syntax errors.

[Quiz] removes mysql reserved keywords from entity

---

src/plugin/announcement/Listener/Resource/AnnouncementListener.php

[Announcement] fixes all announcements visible in every resource

---

src/main/app/API/Utils/FileBag.php
src/main/app/Manager/File/ArchiveManager.php
src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
src/main/core/Listener/Resource/Types/FileListener.php
src/main/core/Resources/config/config.yml
src/main/core/Resources/modules/workspace/components/main.jsx
src/main/core/Subscriber/Tool/ResourcesSubscriber.php

[File] fixes resource transfer

---

src/plugin/drop-zone/Controller/API/DropController.php

[Dropzone] fixes navigation between drops

---

src/main/evaluation/Controller/WorkspaceEvaluationController.php

[Evaluation] fixes ws evaluations list

---

src/plugin/claco-form/Manager/ExportManager.php

[ClacoForm] fixes pdf export for date values

---

src/plugin/claco-form/Manager/ExportManager.php

[ClacoForm] fixed export with date field

---

src/plugin/claco-form/Listener/Resource/ClacoFormListener.php
src/plugin/forum/Listener/Resource/ForumListener.php
src/plugin/forum/Messenger/NotifyUsersOnMessageCreatedHandler.php
src/plugin/forum/Subscriber/Crud/SubjectSubscriber.php

[Workspace] fixes copy

---

src/main/core/Subscriber/Tool/ResourcesSubscriber.php
src/plugin/link/Listener/Resource/ResourceListener.php
src/plugin/link/Listener/Resource/Types/ShortcutListener.php
src/plugin/link/Resources/config/config.yml
src/plugin/link/Resources/config/services/listener.yml
src/plugin/link/Resources/modules/plugin.js
src/plugin/link/Resources/modules/resource/actions/shortcuts.js

[Shortcut] fixes resource import/export

---

src/main/transfer/Resources/config/config.yml
src/main/transfer/Resources/modules/tools/transfer/export/components/details.jsx
src/main/transfer/Resources/translations/actions.en.json
src/main/transfer/Resources/translations/actions.fr.json
src/main/transfer/Security/Voter/ExportFileVoter.php
src/main/transfer/Serializer/ExportFileSerializer.php

[Transfer] adds export refresh right

---

src/main/core/Subscriber/Crud/WorkspaceSubscriber.php
src/main/core/Transfer/Exporter/Workspace/ListManagersExporter.php
src/main/core/Transfer/Exporter/Workspace/ListUsersExporter.php

fixes transfer

---

src/main/transfer/Manager/TransferManager.php

[Transfer] fixes export update

---

src/main/evaluation/Resources/config/services.yml

[Evaluation] registers command services

---

src/plugin/announcement/Entity/Announcement.php
src/plugin/forum/Subscriber/Crud/SubjectSubscriber.php

[Workspace] fixes import

---

src/main/community/Controller/UserController.php
src/main/core/Resources/modules/user/actions/password-reset.js

[Community] changes template used for password initialization

---

src/main/app/Resources/modules/modals/form/components/data.jsx
src/plugin/claco-form/Listener/Resource/ClacoFormListener.php

[ClacoForm] fixes fields copy in ws transfer

---

src/main/app/API/SchemaProvider.php
src/main/community/Subscriber/Crud/UserSubscriber.php
src/main/core/API/Serializer/User/UserSerializer.php
src/main/core/Resources/samples/user/csv/valid/create/full.csv
src/main/core/Resources/schemas/facet.json
src/main/core/Resources/schemas/panelFacet.json
src/main/core/Resources/schemas/resource/resource-node.json
src/main/core/Resources/schemas/transfer.json
src/main/core/Resources/schemas/user.json
src/main/core/Resources/schemas/workspace.json
src/plugin/forum/Resources/schemas/message.json
src/plugin/forum/Resources/schemas/subject.json
src/plugin/open-badge/Resources/schemas/badge.json
src/plugin/path/Resources/schemas/path.json
src/plugin/path/Resources/schemas/step.json
src/plugin/planned-notification/Resources/schemas/planned-notification.json
src/plugin/wiki/Resources/schemas/section.json

[Community] fixes organizations in import

---

src/main/community/Security/Voter/GroupVoter.php

[Community] fixes group visibility for orga managers

---

src/main/core/Transfer/Importer/Workspace/Create.php

[Workspace] fixes import when managers do not exist

---

src/main/core/Resources/config/services/importer.yml
src/main/core/Resources/samples/workspace/csv/valid/empty_role/by_code.csv
src/main/core/Resources/samples/workspace/csv/valid/empty_role/by_id.csv
src/main/core/Resources/translations/transfer.en.json
src/main/core/Resources/translations/transfer.fr.json
src/main/core/Transfer/Importer/Workspace/AddGroup.php
src/main/core/Transfer/Importer/Workspace/EmptyRole.php

[Transfer] adds importer to empty a workspace role

---

src/main/core/Resources/less/content/index.less

[TinyMce] fixes img overflow

---

src/main/app/API/Crud.php
src/main/core/Entity/User.php

[Community] fixes user organization removal

---

src/main/core/Transfer/Importer/Directory/Create.php
src/main/core/Transfer/Importer/Directory/CreateOrUpdate.php

[Transfer] fixes directory importer

---

src/main/app/Resources/modules/layout/sections/home/components/content.jsx
src/main/app/Resources/modules/page/components/content.jsx
src/main/core/Resources/less/layout/pages.less

[Home] fixes html rendering

---

src/main/app/Security/ObjectCollection.php
src/main/community/Security/Voter/RoleVoter.php
src/main/core/Entity/AbstractRoleSubject.php
src/main/core/Entity/User.php
src/main/core/Manager/Workspace/WorkspaceManager.php
src/main/core/Resources/modules/tools/community/user/components/users.jsx
src/main/core/Security/Voter/AbstractVoter.php

[Community] fixes role management

---

src/integration/big-blue-button/Manager/ServerManager.php
src/main/core/Controller/APINew/Workspace/WorkspaceController.php
src/main/core/Entity/Resource/ResourceNode.php
src/main/core/Installation/Migrations/pdo_mysql/Version20220922111929.php
src/main/core/Manager/Workspace/TransferManager.php
src/main/core/Messenger/CopyWorkspaceHandler.php
src/main/core/Messenger/Message/CopyWorkspace.php
src/main/core/Resources/config/services/messenger.yml

fixes workspaces copy

---

src/main/core/API/Serializer/User/UserSerializer.php
src/main/core/Manager/Workspace/TransferManager.php
src/main/core/Subscriber/Tool/ResourcesSubscriber.php

[Workspace] fixes resources copy

---

src/main/core/Subscriber/Crud/ResourceNodeSubscriber.php

Resources were not correctly linked to their poster & thumbnail.

[Resource] fixes poster and thumbnail

---

src/main/core/Resources/modules/resource/actions/copy.js

[Resource] fixes parent reload on copy

---

src/main/core/API/Finder/Workspace/WorkspaceFinder.php
src/main/core/Controller/APINew/Model/HasGroupsTrait.php
src/main/core/Controller/APINew/Model/HasOrganizationsTrait.php
src/main/core/Controller/APINew/Model/HasRolesTrait.php
src/main/core/Controller/APINew/Model/HasUsersTrait.php
src/main/core/Controller/APINew/Model/HasWorkspacesTrait.php
src/main/core/Controller/APINew/Workspace/WorkspaceController.php

[Workspace] fixes managed workspaces accesses

---

src/plugin/path/Controller/PathController.php

[Path] fixes evaluation access in dashboard

---

src/plugin/home/Serializer/HomeTabSerializer.php

[Home] fixes sub tabs copy on workspace copy

---

src/integration/big-blue-button/Resources/modules/resources/bbb/player/components/player.jsx
src/main/app/Resources/modules/content/components/iframe.jsx
src/main/core/Resources/less/layout/components/iframes.less
src/main/core/Resources/less/layout/pages.less
src/plugin/scorm/Resources/modules/resources/scorm/player/components/player.jsx
src/plugin/url/Model/Url.php
src/plugin/url/Resources/modules/components/display.jsx
src/plugin/url/Resources/modules/resources/url/player/components/player.jsx

enhances iframe display

---

src/main/core/Resources/translations/platform.de.json
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.es.json
src/main/core/Resources/translations/platform.fr.json
src/main/core/Resources/translations/platform.nl.json
src/plugin/exo/Resources/modules/items/graphic/components/player.jsx
src/plugin/exo/Resources/modules/items/words/components/editor.jsx
src/plugin/exo/Resources/translations/quiz.nl.json
src/plugin/path/Resources/translations/path.nl.json

[Quiz] fixes keywords edition

---

src/main/core/API/Serializer/User/UserSerializer.php

[Community] fixes user minimal structure for json validation

---

public/index.php
public/maintenance.html

simplifies maintenance page

---

src/main/core/Listener/AuthenticationFailureHandler.php
src/main/core/Repository/User/UserRepository.php
src/main/core/Repository/WorkspaceRepository.php
src/main/core/Resources/config/services/exporter.yml
src/main/core/Tests/Database/Repository/User/UserRepositoryTest.php
src/main/core/Transfer/Exporter/Workspace/ListManagersExporter.php
src/plugin/exo/Controller/Item/ShareController.php

[Transfer] enhances ws managers exporter

---

src/plugin/pdf-player/Controller/EvaluationController.php
src/plugin/pdf-player/Listener/File/Type/PdfListener.php
src/plugin/pdf-player/Manager/EvaluationManager.php
src/plugin/pdf-player/Resources/config/services.yml

[PDF] cleans evaluation management

---

src/main/app/Resources/config/suggested/doctrine_prod.yml
src/main/app/Resources/config/suggested/framework_prod.yml

enables doctrine caches

---

src/main/evaluation/Manager/WorkspaceEvaluationManager.php

[Workspace] only uses evaluated resources for score

---

src/main/app/Resources/modules/page/components/full.jsx
src/main/core/Resources/less/layout/pages.less
src/main/core/Resources/translations/resource.fr.json
src/main/evaluation/Manager/AbstractEvaluationManager.php
src/plugin/path/Manager/EvaluationManager.php
src/plugin/pdf-player/Manager/EvaluationManager.php

Debug 13.6

---

src/main/core/Installation/Updater/Updater130600.php

fixes old plugins removal

---

package.json

upgrades node and npm versions

---

src/plugin/home/Resources/modules/tools/home/store/selectors.js

[Home] fixes workspace default tab

---

src/main/core/API/Serializer/User/UserSerializer.php
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php

This is just a quickfix. It is correctly fixed by https://github.com/claroline/Claroline/commit/ce23abdd36676a2b2bec8e84c79258c05b7079ba.

[Evaluation] fixes ws evaluation export performances

---

src/main/core/Listener/Resource/Types/FileListener.php
src/main/core/Manager/Workspace/TransferManager.php
src/plugin/web-resource/Listener/WebResourceListener.php
src/plugin/web-resource/Resources/config/services.yml

[File] fixes workspace copy

---

src/main/core/Listener/Resource/Types/FileListener.php
src/main/core/Manager/Workspace/TransferManager.php
src/plugin/web-resource/Listener/WebResourceListener.php
src/plugin/web-resource/Resources/config/services.yml

[File] fixes workspace copy (13.6)

---

src/main/evaluation/Controller/WorkspaceEvaluationController.php
src/main/evaluation/Messenger/Message/RecomputeWorkspaceEvaluations.php
src/main/evaluation/Messenger/RecomputeWorkspaceEvaluationsHandler.php
src/main/evaluation/Resources/config/services/messenger.yml
src/main/evaluation/Resources/modules/tools/evaluation/components/parameters.jsx
src/main/evaluation/Resources/translations/evaluation.en.json
src/main/evaluation/Resources/translations/evaluation.fr.json

[Evaluation] adds recompute ws evaluation in ui

---

src/main/community/Finder/RoleFinder.php
src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
src/main/core/Entity/Workspace/Workspace.php
src/main/core/Installation/Migrations/pdo_mysql/Version20221102054906.php
src/main/core/Resources/modules/modals/groups/components/modal.jsx
src/main/core/Resources/modules/modals/roles/components/modal.jsx
src/main/core/Resources/modules/modals/users/components/modal.jsx
src/main/core/Resources/modules/tools/community/group/components/tab.jsx
src/main/core/Resources/modules/tools/community/user/components/tab.jsx
src/main/core/Resources/modules/workspace/actions/view-as.js
src/main/core/Resources/modules/workspace/components/form.jsx
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json
src/main/core/Resources/translations/resource.en.json
src/main/core/Resources/translations/resource.fr.json
src/main/core/Resources/translations/workspace.en.json
src/main/evaluation/Manager/WorkspaceEvaluationManager.php
src/main/evaluation/Resources/translations/workspace.en.json
src/main/evaluation/Resources/translations/workspace.fr.json
src/plugin/drop-zone/Resources/modules/resources/dropzone/editor/components/editor.jsx
src/plugin/drop-zone/Resources/translations/dropzone.en.json
src/plugin/drop-zone/Resources/translations/dropzone.nl.json

| Fixed issues | #2273 
fix #2273

[Evaluation] adds workspace success condition

---

src/plugin/path/Manager/EvaluationManager.php

[Path] fixes path evaluation

---

src/main/core/Installation/Migrations/pdo_mysql/Version20221102054906.php
src/main/evaluation/Controller/WorkspaceEvaluationController.php
src/main/evaluation/Manager/WorkspaceEvaluationManager.php
src/main/evaluation/Messenger/InitializeResourceEvaluationsHandler.php
src/main/evaluation/Messenger/InitializeWorkspaceEvaluationsHandler.php
src/main/evaluation/Messenger/Message/InitializeResourceEvaluations.php
src/main/evaluation/Resources/config/services/controller.yml
src/main/evaluation/Resources/config/services/manager.yml
src/main/evaluation/Resources/config/services/messenger.yml
src/main/evaluation/Subscriber/ResourceEvaluationSubscriber.php
src/main/evaluation/Subscriber/WorkspaceEvaluationSubscriber.php

[Workspace] fixes evaluation calculation

---

src/main/evaluation/Manager/PdfManager.php
src/main/evaluation/Resources/views/template/workspace_success_certificate.en.pdf.twig

[Workspace] fixes evaluation certificates

---

src/main/app/Resources/modules/data/types/image/components/input.jsx
src/main/app/Resources/translations/actions.en.json
src/main/app/Resources/translations/actions.fr.json
src/main/app/Resources/translations/platform.en.json
src/main/app/Resources/translations/platform.fr.json
src/main/core/API/Serializer/Platform/ClientSerializer.php
src/main/core/API/Serializer/Resource/ResourceTypeSerializer.php
src/main/core/Configuration/LegacyParametersMapping.php
src/main/core/Resources/modules/resource/components/form.jsx

fixes image input when file is missing

---

src/main/transfer/DependencyInjection/ClarolineTransferExtension.php
src/main/transfer/Installation/ClarolineTransferInstaller.php
src/main/transfer/Installation/Updater/Updater130601.php
src/main/transfer/Manager/TransferManager.php
src/main/transfer/Resources/config/parameters.yml
src/main/transfer/Resources/config/services/manager.yml
src/main/transfer/Resources/config/services/subscriber.yml
src/main/transfer/Resources/config/services/transfer.yml
src/main/transfer/Resources/config/services/updater.yml
src/main/transfer/Subscriber/Crud/ExportFileSubscriber.php

[Transfer] moves logs in files dir

---

src/main/app/Entity/Meta/Creator.php
src/main/core/API/Serializer/File/PublicFileSerializer.php
src/main/core/Controller/APINew/FileController.php
src/main/core/Controller/FileController.php
src/main/core/Entity/File/PublicFile.php
src/main/core/Entity/File/PublicFileUse.php
src/main/core/Entity/Resource/File.php
src/main/core/Installation/Migrations/pdo_mysql/Version20221110093235.php
src/main/core/Manager/FileManager.php
src/main/core/Subscriber/Crud/File/PublicFileSubscriber.php
src/plugin/exo/Serializer/Item/Type/GraphicQuestionSerializer.php

[File] updates api

---

src/main/app/Resources/modules/action/utils.js

[UI] avoids creating more menu if there is only one action

---

src/plugin/claco-form/Listener/Resource/ClacoFormListener.php
src/plugin/claco-form/Subscriber/EntrySubscriber.php

[ClacoForm] fixes entries creator

---

src/main/core/API/Finder/Workspace/WorkspaceFinder.php
src/main/core/Controller/APINew/Workspace/WorkspaceController.php
src/main/core/Listener/DataSource/Workspace/AllSource.php
src/main/core/Listener/DataSource/Workspace/RegisteredSource.php

[Workspace] fixes lists performances

---

src/main/core/API/Finder/Workspace/WorkspaceFinder.php
src/main/core/Controller/APINew/Workspace/WorkspaceController.php
src/main/core/Listener/DataSource/Workspace/AllSource.php
src/main/core/Listener/DataSource/Workspace/RegisteredSource.php

[Workspace] fixes lists performances (13.7)

---

src/plugin/scorm/Resources/modules/resources/scorm/player/containers/player.jsx

[Scorm] fixes init for anonymous users

---

src/plugin/scorm/Resources/modules/resources/scorm/player/containers/player.jsx

[Scorm] fixes init for anonymous users (13.7)

---

src/main/app/API/Finder/AbstractFinder.php
src/main/app/API/Finder/FinderFilterInterface.php
src/main/app/Resources/config/services/finder.yml
src/main/community/Command/CreateCommand.php
src/main/community/Finder/Filter/UserFilter.php
src/main/community/Finder/UserFinder.php
src/main/community/Resources/config/services/finder.yml
src/main/core/Entity/User.php
src/main/core/Installation/Migrations/pdo_mysql/Version20221125070109.php
src/main/core/Manager/RoleManager.php
src/main/core/Manager/UserManager.php
src/main/core/Repository/User/UserRepository.php
src/main/core/Tests/Database/Repository/User/UserRepositoryTest.php
src/main/evaluation/Finder/ResourceUserEvaluationFinder.php
src/main/evaluation/Finder/WorkspaceEvaluationFinder.php
src/plugin/cursus/Finder/EventPresenceFinder.php
src/plugin/cursus/Finder/Registration/CourseUserFinder.php
src/plugin/cursus/Finder/Registration/EventUserFinder.php
src/plugin/cursus/Finder/Registration/SessionUserFinder.php
src/plugin/drop-zone/Finder/DropFinder.php
src/plugin/exo/Finder/PaperFinder.php
src/plugin/open-badge/Finder/AssertionFinder.php
src/plugin/open-badge/Transfer/Exporter/AssertionListExporter.php
src/plugin/scorm/Finder/ScoTrackingFinder.php

[Community] introduces technical users

---

src/main/transfer/Manager/TransferManager.php

[Transfer] fixes export files access

---

src/main/core/Resources/modules/user/components/micro.jsx

[Community] fixes user name display

---

src/main/core/Installation/Migrations/pdo_mysql/Version20221130090000.php
src/main/core/Resources/views/template/email_layout.en.html.twig
src/main/core/Resources/views/template/email_layout.fr.html.twig

Debug 13.6.1

---

src/main/core/Installation/Migrations/pdo_mysql/Version20221130090000.php
src/main/core/Resources/views/template/email_layout.en.html.twig
src/main/core/Resources/views/template/email_layout.fr.html.twig

Debug 13.7

---

src/plugin/open-badge/Serializer/BadgeClassSerializer.php

[Badge] fixes description prop

---

src/plugin/open-badge/Serializer/BadgeClassSerializer.php

[Badge] fixes description prop (13.7)

---

src/main/core/Resources/less/data/card.less

fixes data cards description display

---

src/main/core/Resources/modules/widget/utils.js

[Home] fixes widgets background

---

src/plugin/home/Resources/modules/tools/home/store/selectors.js

[Home] fixes workspace tab creation

---

src/main/core/Controller/ResourceController.php

[Resource] fixes resource open with restrictions

---

src/main/core/Controller/ResourceController.php

[Resource] fixes resource open with restrictions (13.7)

---

src/plugin/cursus/Manager/EventManager.php

[Training] fixes event invitations always sent

---

src/plugin/cursus/Manager/EventManager.php

[Training] fixes event invitations always sent (13.7)

---

src/main/scheduler/Serializer/ScheduledTaskSerializer.php
src/main/transfer/Manager/TransferManager.php
src/main/transfer/Subscriber/Crud/ExportFileSubscriber.php
src/main/transfer/Subscriber/Crud/ImportFileSubscriber.php

[Transfer] fixes scheduler integration

---

src/main/scheduler/Serializer/ScheduledTaskSerializer.php
src/main/transfer/Manager/TransferManager.php
src/main/transfer/Subscriber/Crud/ExportFileSubscriber.php
src/main/transfer/Subscriber/Crud/ImportFileSubscriber.php

[Transfer] fixes scheduler integration (13.7)

---

src/main/scheduler/Repository/ScheduledTaskRepository.php

[Scheduler] fixes tasks retrieve

---

src/main/scheduler/Repository/ScheduledTaskRepository.php

[Scheduler] fixes tasks retrieve (13.7)

---

src/main/core/Command/UpdateRichTextCommand.php
src/plugin/path/Entity/Path/Path.php
src/plugin/path/Installation/Migrations/pdo_mysql/Version20230104082218.php
src/plugin/path/Listener/Resource/PathListener.php
src/plugin/path/Resources/config/services/serializer.yml
src/plugin/path/Resources/modules/resources/path/components/overview.jsx
src/plugin/path/Resources/modules/resources/path/editor/components/main.jsx
src/plugin/path/Resources/modules/resources/path/editor/components/parameters.jsx
src/plugin/path/Resources/modules/resources/path/prop-types.js
src/plugin/path/Resources/styles/resources/path/index.less
src/plugin/path/Serializer/PathSerializer.php
src/plugin/path/Serializer/StepSerializer.php

[Path] adds a resource on overview

---

src/main/evaluation/Resources/modules/tools/evaluation/components/users.jsx
src/main/evaluation/Resources/modules/tools/evaluation/containers/users.jsx
src/main/evaluation/Resources/modules/tools/evaluation/store/actions.js

[Evaluation] allows to download multiple certificates at once

---

src/main/scheduler/Repository/ScheduledTaskRepository.php

[Scheduler] fixes recurring tasks

---

src/plugin/exo/Resources/modules/items/pair/index.js

[Quiz] fixes error display in pair question

---

src/plugin/exo/Resources/modules/items/components/editor.jsx

[Quiz] fixes items edition

---

src/plugin/exo/Resources/modules/items/ordering/index.js

[Quiz] fixes ordering item copy

---

src/integration/peertube/Resources/modules/components/player.jsx
src/main/core/Manager/CurlManager.php

[PeerTube] hides useless player elements

---

docs/sections/themes.md

updates documentation

---

src/main/core/API/Serializer/Platform/ClientSerializer.php
src/main/core/Configuration/PlatformDefaults.php
src/main/core/Controller/APINew/FileController.php
src/main/core/Installation/Migrations/pdo_mysql/Version20230129092146.php
src/main/core/Resources/config/services/controller.yml
src/main/core/Resources/modules/tinymce/config.js

disallows script tags in tinyMCE content

---

src/main/evaluation/Controller/WorkspaceEvaluationController.php
src/main/evaluation/Manager/PdfManager.php
src/main/evaluation/Manager/WorkspaceEvaluationManager.php
src/main/evaluation/Resources/modules/tools/evaluation/components/user.jsx
src/main/evaluation/Resources/modules/tools/evaluation/components/users.jsx
src/main/evaluation/Resources/views/template/workspace_success_certificate.fr.pdf.twig

[Evaluation] fixes workspace evaluation access rights

---

src/main/core/Installation/Migrations/pdo_mysql/Version20230129080754.php

I've missed the case where a main organization link is duplicated.

[Community] fixes user organization migration

---

src/main/core/Controller/APINew/FileController.php

checks file blacklist in image upload endpoint too

---

src/integration/peertube/Manager/EvaluationManager.php
src/integration/peertube/Resources/modules/resources/video/components/menu.jsx
src/main/evaluation/Manager/WorkspaceEvaluationManager.php
src/main/evaluation/Resources/translations/evaluation.fr.json
src/plugin/path/Resources/modules/resources/path/components/summary.jsx
src/plugin/path/Resources/modules/resources/path/player/components/end.jsx
src/plugin/path/Resources/modules/resources/path/player/components/main.jsx
src/plugin/path/Resources/modules/resources/path/player/containers/main.jsx
src/plugin/video-player/Manager/EvaluationManager.php

[Evaluation] fixes calculation

---

src/plugin/drop-zone/Resources/modules/resources/dropzone/components/corrections.jsx

[Dropzone] fixes display of corrector

---

docs/sections/application/plugins.md

[Documentation] updates plugin section

---

changelogs/changelog-13.7.en.md
changelogs/changelog-13.7.fr.md

Changelog 13.7

---

src/main/app/Resources/modules/intl/number/index.js

adds missing percent function

---

src/main/community/Resources/modules/profile/components/edit.jsx
src/main/community/Resources/modules/profile/containers/edit.jsx
src/main/community/Resources/modules/profile/utils.js

Debug community

---

src/main/core/Command/UpdateRichTextCommand.php

fixes RichTextUpdate command

---

src/plugin/forum/Finder/SubjectFinder.php

[Forum] adds default sort on subject titles

---

src/main/core/Listener/DataSource/Workspace/AllSource.php
src/main/core/Resources/modules/data/sources/workspaces.js
src/plugin/cursus/Listener/DataSource/AllCoursesSource.php
src/plugin/cursus/Listener/DataSource/EventsSource.php
src/plugin/cursus/Listener/DataSource/PublicSessionSource.php
src/plugin/cursus/Listener/DataSource/SessionSource.php
src/plugin/cursus/Resources/modules/data/sources/courses.js
src/plugin/cursus/Resources/modules/data/sources/events.js
src/plugin/cursus/Resources/modules/data/sources/sessions.js
src/plugin/open-badge/Listener/DataSource/BadgesSource.php
src/plugin/open-badge/Resources/modules/data/sources/badges.js

fixes organization filter for data sources

---

src/main/core/Resources/modules/resource/components/end.jsx
src/main/evaluation/Resources/modules/tools/evaluation/components/user.jsx
src/main/evaluation/Resources/modules/tools/evaluation/components/users.jsx

[Evaluation] shows evaluation certificate for success only

---

src/main/community/Resources/modules/tools/community/role/store/actions.js
src/main/core/Listener/DataSource/Workspace/AllSource.php
src/main/core/Resources/modules/data/sources/workspaces.js
src/main/core/Resources/modules/resource/components/end.jsx
src/main/evaluation/Resources/modules/tools/evaluation/components/user.jsx
src/main/evaluation/Resources/modules/tools/evaluation/components/users.jsx
src/plugin/agenda/Resources/modules/data/sources/events.js
src/plugin/agenda/Resources/modules/data/sources/tasks.js
src/plugin/cursus/Listener/DataSource/AllCoursesSource.php
src/plugin/cursus/Listener/DataSource/EventsSource.php
src/plugin/cursus/Listener/DataSource/PublicSessionSource.php
src/plugin/cursus/Listener/DataSource/SessionSource.php
src/plugin/cursus/Resources/modules/data/sources/courses.js
src/plugin/cursus/Resources/modules/data/sources/events.js
src/plugin/cursus/Resources/modules/data/sources/sessions.js
src/plugin/open-badge/Listener/DataSource/BadgesSource.php
src/plugin/open-badge/Resources/modules/data/sources/badges.js
src/plugin/path/Installation/Migrations/pdo_mysql/Version20230228160000.php

Merge 13.7 into main

---

src/main/evaluation/Manager/WorkspaceEvaluationManager.php

[Evaluation] fixes ws max failed condition

---

src/plugin/cursus/Finder/Registration/CourseUserFinder.php
src/plugin/cursus/Finder/Registration/EventUserFinder.php
src/plugin/cursus/Finder/Registration/SessionUserFinder.php

[Training] fixes participants list

---

docs/sections/application/tools.md

[Documentation] updates tool section

---

docs/sections/application/tools.md

[Documentation] fixes tool section

---

docs/sections/user-interface/tools.md

[Documentation] fixes typo

---

docs/sections/user-interface/tools.md

[Documentation] updates tool store section

---

src/main/app/API/FinderProvider.php
src/main/community/Transfer/Exporter/Group/ListUsersExporter.php

[Transfer] adds group info in group_list_users export

---

src/main/app/API/FinderProvider.php
src/main/community/Transfer/Exporter/Group/ListUsersExporter.php

[Transfer] adds group info in group_list_users export (13.7)

---

src/main/example/Controller/ExampleController.php
src/main/example/DependencyInjection/ClarolineExampleExtension.php
src/main/example/Entity/Example.php
src/main/example/Installation/ClarolineExampleInstaller.php
src/main/example/Installation/Migrations/pdo_mysql/Version20230323090533.php
src/main/example/Resources/config/routing.yml
src/main/example/Resources/config/services.yml
src/main/example/Resources/config/services/controller.yml
src/main/example/Resources/config/services/serializer.yml
src/main/example/Resources/modules/tools/example/components/tool.jsx
src/main/example/Resources/modules/tools/example/modals/parameters/components/modal.jsx
src/main/example/Resources/modules/tools/example/modals/parameters/containers/modal.jsx
src/main/example/Resources/modules/tools/example/modals/parameters/index.js
src/main/example/Resources/modules/tools/example/modals/parameters/store/index.js
src/main/example/Resources/modules/tools/example/modals/parameters/store/reducer.js
src/main/example/Resources/modules/tools/example/modals/parameters/store/selectors.js
src/main/example/Serializer/ExampleSerializer.php

[Example] adds model and form

---

src/main/evaluation/Manager/PdfManager.php

[Evaluation] fixes score in certificates

---

src/plugin/cursus/Resources/modules/tools/trainings/catalog/components/creation.jsx
src/plugin/cursus/Resources/modules/tools/trainings/catalog/components/list.jsx
src/plugin/cursus/Resources/modules/tools/trainings/catalog/components/main.jsx
src/plugin/cursus/Resources/modules/tools/trainings/catalog/store/actions.js

[Training] fixes course form

---

src/main/community/Transfer/Importer/User/Create.php
src/main/community/Transfer/Importer/User/Update.php

[Transfer] fixes user organizations import

---

src/plugin/cursus/Entity/Course.php

[Training] fixes entity typing

---

src/plugin/exo/Manager/ExerciseManager.php

[Quiz] fixes csv exports

---

src/main/core/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/main/theme/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/plugin/exo/Manager/ExerciseManager.php
src/plugin/home/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/plugin/lesson/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/plugin/open-badge/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/plugin/path/Installation/Migrations/pdo_mysql/Version20230426080000.php

Merge 13.8 into main

---

src/main/core/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/main/core/Installation/Migrations/pdo_mysql/Version20230426120000.php

drops more obsolete tables from DB (main)

---

src/integration/peertube/Resources/modules/components/player.jsx
src/integration/peertube/Resources/modules/resources/video/components/player.jsx
src/plugin/video-player/Resources/modules/files/video/components/player.jsx

[Video] updates progression on time update

---

src/integration/peertube/Resources/modules/components/player.jsx
src/integration/peertube/Resources/modules/resources/video/components/player.jsx
src/plugin/video-player/Resources/modules/files/video/components/player.jsx

[Video] updates progression on time update (13.7)

---

src/plugin/cursus/Entity/Course.php
src/plugin/cursus/Installation/ClarolineCursusInstaller.php
src/plugin/cursus/Installation/Updater/Updater130800.php
src/plugin/cursus/Resources/config/services/updater.yml
src/plugin/cursus/Resources/modules/course/components/about.jsx
src/plugin/cursus/Resources/modules/course/components/parameters.jsx

[Training] displays duration in hours

---

src/plugin/claco-form/Resources/modules/resources/claco-form/player/store/reducer.js

[ClacoForm] fixes list page size option

---

src/plugin/path/Installation/Migrations/pdo_mysql/Version20230426080000.php

fixes migrations

---

src/main/core/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/plugin/path/Installation/Migrations/pdo_mysql/Version20230426080000.php

fixes old tables deletion

---

src/main/core/Installation/Migrations/pdo_mysql/Version20230426080000.php

fixes old tables deletion (again)

---

src/main/evaluation/Manager/PdfManager.php

[Evaluation] fixes pdf certificate

---

src/plugin/cursus/Installation/Migrations/pdo_mysql/Version20210406073812.php

[Trainings] fixes migrations

---

src/main/core/Resources/less/layout/components/icons.less

[Theme] fixes icons preview

---

src/main/core/Resources/modules/resource/components/end.jsx

[Quiz] fixes endpage for anonymous

---

src/main/community/Finder/Filter/UserFilter.php
src/plugin/exo/Finder/PaperFinder.php

[Quiz] fixes papers list

---

src/plugin/path/Manager/EvaluationManager.php

[Path] fixes progression

---

src/plugin/claco-form/Event/Log/LogFieldCreateEvent.php
src/plugin/claco-form/Event/Log/LogFieldEditEvent.php
src/plugin/claco-form/Manager/ClacoFormManager.php
src/plugin/claco-form/Manager/ExportManager.php

[ClacoForm] fixes export

---

src/plugin/claco-form/Resources/modules/resources/claco-form/player/components/entry-form.jsx

[ClacoForm] fixes entry submission

---

src/main/community/Resources/modules/actions/user/password-reset.js
src/main/community/Resources/translations/actions.en.json
src/main/community/Resources/translations/actions.fr.json

| Fixed issues  | N/A
Added messages for reset password modal

[Community] adds confirm message for password reset

---

src/main/theme/Resources/modules/administration/appearance/modals/color-chart-parameters/components/modal.jsx

| New feature?  | /no
| BC breaks?    | /no

[Theme] fixes custom color charts

---

src/plugin/exo/Resources/modules/items/choice/index.js
src/plugin/exo/Resources/modules/items/cloze/index.js
src/plugin/exo/Resources/modules/items/components/editor.jsx
src/plugin/exo/Resources/modules/items/graphic/index.js
src/plugin/exo/Resources/modules/items/grid/index.js
src/plugin/exo/Resources/modules/items/match/index.js
src/plugin/exo/Resources/modules/items/ordering/index.js
src/plugin/exo/Resources/modules/items/pair/index.js
src/plugin/exo/Resources/modules/items/selection/index.js
src/plugin/exo/Resources/modules/items/set/index.js
src/plugin/exo/Resources/modules/items/words/index.js
src/plugin/exo/Resources/modules/resources/quiz/editor/components/step.jsx
src/plugin/exo/Resources/modules/resources/quiz/editor/containers/main.jsx
src/plugin/exo/Resources/modules/resources/quiz/utils.js

[Quiz] fixes items copy

---

docs/sections/application/plugins.md

[Documention] fixes typo

---

src/integration/peertube/Resources/modules/resources/video/containers/editor.jsx

[Peertube] fixes editor redirection

---

src/integration/youtube/Resources/modules/resources/video/containers/editor.jsx
src/integration/youtube/Serializer/VideoSerializer.php

- Managed of additional URL params,
- Redirect to video on exit.

[Youtube] fixes small bugs

---

src/main/core/Resources/less/layout/components/color-charts.less
src/main/theme/Resources/modules/color/components/library.jsx

| New feature?  | yno
- Added scrollbar and margin for select color chart.

[Theme] fixes color picker display

---

docs/_data/sections.yml
docs/sections/application/parameters.md
docs/sections/application/templates.md

[Documentation] fixes navigation

---

src/main/core/Resources/modules/administration/template/components/menu.jsx
src/main/core/Resources/translations/platform.en.json
src/main/core/Resources/translations/platform.fr.json

[Template] adds 'other' type

---

src/plugin/exo/Controller/ItemController.php
src/plugin/exo/Resources/modules/items/components/list.jsx

[Quiz] fixes question import

---

src/main/core/Resources/config/services/updater.yml

[Core] removes wrong updater definition

---

.github/workflows/ci.yml
.php_cs
composer.json
composer.lock
docs/sections/dev/best-practices.md
docs/sections/dev/code-analysis.md
docs/sections/dev/commands.md
src/main/app/Resources/config/suggested/sensio_framework_extra.yml

upgrades php-cs-fixer

---

docs/sections/user-interface/parameters.md

- Added state to configSelectors.param.

[Documentation] fixed typo parameters method

---

src/main/community/Resources/modules/organization/modals/about/components/modal.jsx
src/main/core/Resources/modules/resource/modals/about/components/about.jsx
src/main/core/Resources/modules/workspace/modals/about/components/modal.jsx

[Resource] Display resource code in modal

---

src/plugin/path/Resources/modules/resources/path/components/overview.jsx
src/plugin/path/Resources/modules/resources/path/components/summary.jsx
src/plugin/path/Resources/modules/resources/path/containers/overview.jsx
src/plugin/path/Resources/modules/resources/path/player/components/menu.jsx
src/plugin/path/Resources/modules/resources/path/player/containers/menu.jsx
src/plugin/path/Resources/modules/resources/path/store/selectors.js

- Added home page & end page in summary
- Added step numbering home page summary

[Path] Display home/end page in summary

---

src/main/core/Controller/APINew/Resource/ResourceNodeController.php
src/main/core/Resources/modules/resource/modals/parameters/containers/modal.jsx
src/main/core/Resources/modules/resource/modals/parameters/store/actions.js
src/main/core/Resources/modules/resource/modals/parameters/store/index.js

[Resource] full node loading in resource config

---

src/main/core/Installation/Updater/Updater140000.php
src/main/core/Resources/config/services/updater.yml

fixes 14.0 installation

---

src/main/app/Resources/modules/content/search/components/unified.jsx
src/main/core/Resources/modules/resource/components/rights.jsx
src/main/core/Resources/styles/components/_resources.scss
src/main/example/Resources/modules/tools/example/components/form.jsx
src/plugin/tag/Resources/modules/components/typeahead.jsx
src/plugin/tag/Resources/modules/data/types/tag/components/input.jsx
src/plugin/tag/Resources/styles/index.scss

fixes ui bugs

---

changelogs/changelog-14.0.en.md
changelogs/changelog-14.0.fr.md

creates 14.0 changelog
