app/console

As with Symfony 2.7 there are a lot of deprecated to prepare the 3.0 version we see a lot of deprecated when executing the console script.
This update remove the display of the deprecated.

Deactivate deprecated

---

composer.json
composer.lock

It's needed by a lot of legacy tests (with some of them still working).

Add mockery as dev dependency

---

app/console
scripts/check.php
web/app.php
web/maintenance.php

The following error reporting flag in app/console is incorrect:
`Debug::enable(E_ALL ^ ~E_DEPRECATED);`
The result is that sometimes php crashes silently instead of throwing fatal errors...
The correct form would be `E_ALL & ~E_DEPRECATED` but it doesn't look like deprecation messages should be removed at all from the dev environment, so I left it on its default value (`E_ALL`).
This PR also fixes a logic error in scripts/check.php and applies php-cs fixes coming from claroline/Distribution.

Remove erroneous report flag + fix version check

---

package.json

For some reason, executing node commands in npm scripts sometimes leads to path errors: https://travis-ci.org/claroline/Distribution/builds/129947034#L425.

Replace module commands by explicit/absolute paths

---

composer.json

Move the bin/ folder back into vendor/ so that it can be cached by travis.claroline.com and so that when building a docker image from a travis PR, the build folder is present.

bin/ location

---

composer.json

This is for php 7.1+ compatibility.
https://github.com/mockery/mockery/issues/635
It fixes the crash here: https://github.com/claroline/Distribution/pull/5637

Mockery update

---

.travis.yml

Travis n'utilise pas le même environnement de build que Distribution (je ne sais pas pourquoi) et l'environnement utilisé ne sera bientôt plus supporté par travis.
> This job ran on our Precise environment, which is in the process of being decommissioned. Please update to a newer Ubuntu version by specifying dist: xenial in your .travis.yml.

changes travis build env

---

composer.json

- Removes `phpunit/phpunit` from composer requirements (use simple-phpunit from symfony/phpunit-bridge instead, handles phpunit installation with cross-version compatibility layers). 
- Upgrades to `mockery/mockery: ^1.2`

PHP 7.4 compatibility

---

.travis.yml
README.md
package.json

Done in this PR:
- ✔️ fix composer memory limit
- ✔️ fix NodeJS compatibility with newer libraries by testing with NodeJS 10+
- ✔️ drop support for unmaintained NodeJS versions 6 and 8
- ✔️ drop support for MySQL lower than 8.0 as per Robin's comments
- ✔️ start testing on MySQL 8.0 (previously only 5.7 was tested)
- ✔️ start testing on all supported versions of PHP (TODO after 30 Nov 2020: remove PHP 7.2 and add PHP 8.0)
- ✔️ fix installation commands, change removed `composer build` to `npm run webpack`
- ✔️ add new ENV vars as per new symfony 4.4 requirements
```
- export ENV=PROD
- export APP_ENV=test
- export APP_DEBUG=0
```
- ✔️ add three jobs for all currently supported versions of the technical requirements (MySQL 5.7 is no longer supported, but I cannot find a way to configure …

fix travis build

---

src/main/core/Controller/APINew/Workspace/EvaluationController.php
src/main/core/Controller/APINew/Workspace/RequirementsController.php
src/main/core/Listener/Workspace/EvaluationListener.php
src/main/core/Manager/Workspace/EvaluationManager.php
src/main/core/Resources/config/services/listener.yml
src/main/core/Resources/views/resource/embed/video.html.twig

fixes 13.x

---

src/main/core/Command/Dev/PluginInstallCommand.php
src/main/core/Command/Dev/PluginUninstallCommand.php

Broken since https://github.com/claroline/distribution/pull/6762

[core] Fix missing call to parent::configure() in *PluginCommand

---

src/main/core/Library/Mailing/TransportFactory.php

Because `(bool) 'none' === true` it is no longer possible to disable tls.

fixes mailer encryption parameter

---

.github/workflows/release_patch.yml

| Fixed issues | no
By using the secret `RELEASER_TOKEN` (ClaroBot's token) in the `checkout ` step, we are able to bypass restrictions/required status checks when pushing on protected branches.

Use direct push instead of a PR for releases

---

.github/workflows/dockerimage.yml

The workflow misses the mandatory top-level key `on:`, this adds one. Should fix the alerts about the non runnable workflow that are triggered when merging PRs.

Fix docker-compose GA workflow

---

src/main/kernel/ClarolineKernelBundle.php
src/main/kernel/Manager/BundleManager.php

Running any command produces a wrong cache (all plugins are loaded even though they are not all activated, which is only needed when installing or updating a platform). This PR fixes it.

Fix broken state after cache:clear

---

.docker.dev/mysql/my.cnf
.docker.dev/web/Dockerfile
.docker.dev/web/config/php.ini
.docker.dev/web/entrypoint.sh
.docker.dev/web/files/apache2/claroline-ssl.conf
.docker.dev/web/files/apache2/claroline.conf
.github/workflows/dockerimage.dev.yml
README.md
doc/index.md
doc/sections/docker.md
docker-compose.dev.yml

| Fixed issues | none
Reducing the overhead of contributing to Claroline by providing a predefined environment that can be started using a single `docker-compose` command, thus allowing developers to inspect the UI using browser extensions like [React Devtools](https://github.com/facebook/react/tree/master/packages/react-devtools) and [Redux Devtools](https://github.com/reduxjs/redux-devtools) as well as to see their file changes upon refresh.
By using Docker for development, new contributors can get started faster by focusing on their code changes instead of spending hours setting up their environment for the first time.
It's also a representation of the sequence of steps required to …

[Docker] development setup

---

src/main/core/Manager/ResourceManager.php
src/main/core/Subscriber/Log/FunctionalLogSubscriber.php

This is a quickfix.
Because of https://github.com/claroline/Claroline/blob/13.x/src/main/core/Subscriber/Log/FunctionalLogSubscriber.php#L47, if the log subscriber is not executed before implementations, loaded data is lost.
The correct fix is to remove the call to `$event->setData` in the log event but for now it is required for the generic tool open event. The event has a validation which checks if the event has been populated and throws an exception otherwise.

fixes resources opening

---

src/main/core/Library/Configuration/PlatformDefaults.php
src/plugin/home/Resources/modules/tools/home/components/page.jsx
src/plugin/home/Resources/modules/tools/home/components/tabs.jsx
src/plugin/home/Resources/modules/tools/home/containers/page.jsx
src/plugin/home/Resources/styles/home.less

The following PR makes it possible to show dropdown menus in the top horizontal navigation. This behaviour is controlled by a flag that is used to enable/disable the feature - `show_sub_menu` (defaults to `false`)

Add support and styles for sub tabs in the top navigation

---

src/plugin/saml/Configuration/PlatformDefaults.php
src/plugin/saml/Resources/config/services/security.yml
src/plugin/saml/Security/UserCreator.php

New option is in `platform_options.json` and is `saml.organization_id` (the UUID of the organization to use as main organization for new users).

[Saml] allows to assign users to organization on creation

---

src/main/core/Messenger/ExecuteScheduledTaskHandler.php
src/main/core/Messenger/Message/SendMessage.php
src/main/core/Messenger/SendMessageHandler.php
src/main/core/Resources/config/services/messenger.yml
src/plugin/forum/Messenger/NotifyUsersOnMessageCreatedHandler.php
src/plugin/forum/Resources/config/services/messenger.yml
src/plugin/message/Manager/MessageManager.php

- Remove last direct dependencies to `MessageManager` and use `MessageEvents::MESSAGE_SENDING` event.
- Avoid sending messages to disabled users
- Avoid creating duplicate `MessageLog` if a user is in the receivers list more than once. It can occur if the message is sent to several groups the user is registered in.
- Clean implementation.

fixes message sending

---

composer.json

| New feature?  |  no
This fixes a deprecation notice due to the use of legacy classes from `symfony/messenger` (deprecated in favor of symfony/*-messenger`).
The component has been split into several bridges that can be required independently.

Require symfony/redis-messenger & doctrine-messenger instead of symfony/messenger

---

src/main/core/Manager/CurlManager.php
src/plugin/documentation/Controller/DocumentationController.php

cURL was not configured to follow redirection. So since we've migrated `support.claroline.com`, the online documentation and our support features are broken.
I will need to update default configuration too (will require updaters).

fixes documentation and support integration

---

package.json

| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
This PR fixes a dev build error caused by `isomorphic-form-data`. An update of `swagger-ui-react` is required.
For more information, please, check the closed issue in `swagger-ui` : https://github.com/swagger-api/swagger-ui/issues/7436

fix error in dev build caused by isomorphic-form-data

---

src/main/core/Resources/less/layout/components/popovers.less

| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
This PR uses `white-space: pre` to preserve the original text formatting in popover content
This fixes the issue of having no new lines in Training Price description:

Preserve white spaces in popover content

---

src/main/core/Resources/less/layout/components/popovers.less

| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
Price description before: 
Price description after:

[Trainings] Fix line wrapping in price description tooltip

---

src/main/app/Resources/modules/layout/sections/administration/store/selectors.js

| Fixed issues | #1659
If the default tool of administration is not accessible by the current user, the redirection fails and ends up with a white page.

[Administration] fixes open redirection

---

src/main/core/Controller/APINew/Resource/Types/TextController.php
src/main/core/Resources/config/services/controller.yml
src/main/core/Resources/modules/resources/text/components/resource.jsx
src/main/core/Resources/modules/resources/text/containers/resource.jsx

For now urls for images and ressources are broken in the TinyMce contents.
It's broken for all of our PDF exports.

[Text] adds PDF export

---

src/main/app/Resources/modules/content/list/containers/source.jsx
src/main/app/Resources/modules/content/list/parameters/components/form.jsx
src/main/authentication/Resources/translations/data_sources.fr.json
src/main/evaluation/Finder/ResourceEvaluationFinder.php
src/main/evaluation/Resources/config/config.yml
src/main/evaluation/Resources/config/services/finder.yml
src/main/evaluation/Resources/config/services/serializer.yml
src/main/evaluation/Resources/config/services/subscriber.yml
src/main/evaluation/Resources/modules/data/sources/resource-attempts.js
src/main/evaluation/Resources/modules/data/sources/resource-evaluations.js
src/main/evaluation/Resources/modules/data/sources/workspace-evaluations.js
src/main/evaluation/Resources/modules/plugin.js
src/main/evaluation/Resources/translations/data_sources.en.json
src/main/evaluation/Resources/translations/data_sources.fr.json
src/main/evaluation/Serializer/ResourceEvaluationSerializer.php
src/main/evaluation/Subscriber/DataSource/ResourceAttemptSource.php
src/main/evaluation/Subscriber/DataSource/ResourceEvaluationSource.php
src/main/evaluation/Subscriber/DataSource/WorkspaceEvaluationSource.php

Adds new data sources for : 
- Resource attempts
- Resource evaluations
- Workspace evaluations
All new sources are available for the `desktop` and `workspace` context.
On desktop, users with `ROLE_ADMIN` role see all, others see theirs.
On workspace, users with `ADMINISTRATE` right see all, others see theirs.
We might change it later to check the `ADMINISTRATE` or `EDIT` right on the future evaluation tool.

[Evaluation] adds data sources

---

src/main/core/Entity/Template/Template.php
src/main/core/Installation/Migrations/pdo_mysql/Version20211026053317.php
src/main/core/Installation/Migrations/pdo_mysql/Version20211125072427.php

In MySQL >= 8.0.3 and MariaDB >= MariaDB 10.3.6, `system` is a reserved keyword and is not well escaped by Doctrine causing crashes in those environments.
ping @maieutiquer

[Template] replaces mysql reserved keyword in entity prop

---

src/main/core/Resources/modules/tinymce/plugins/file-upload.js
src/main/core/Resources/modules/tinymce/plugins/resource-picker.js

More a hack than a fix.
We basically wait for JS code to be executed. So it's possible the bug still occurs on device with low performances : we may not wait enough.

[tinymce] fixes selection from resources picker and file upload

---

src/main/core/Resources/server/themes/build.js

| Fixed issues | #1954
We are now deleting only the current resource folder before copying it, not the entire theme folder

[Theme] Fix fonts folder not being copied

---

src/main/core/Security/Voter/GroupVoter.php
src/main/core/Security/Voter/RoleVoter.php

I've closed some endpoints in the last version which caused standard users can't see team members.
It uses the list of users for the member role which is now closed by the `OPEN` right on the role.
The `RoleVoter` has been updated to give this right to the owners of the role. I've updated the `GroupVoter` to make it work the same way.

[Community] fixes role and group access rights

---

src/main/core/Resources/modules/tool/actions/configure.js
src/main/core/Resources/modules/tool/actions/rights.js

| Fixed issues | #1907 
It also hides the "Configure rights" action which is not implemented in home context.

fixes #1907

---

src/main/core/Resources/modules/tools/community/user/components/users.jsx
src/main/evaluation/Finder/ResourceUserEvaluationFinder.php
src/main/evaluation/Finder/WorkspaceEvaluationFinder.php
src/main/evaluation/Resources/modules/data/sources/resource-evaluations.js
src/main/evaluation/Resources/modules/data/sources/workspace-evaluations.js
src/main/evaluation/Resources/modules/tools/evaluation/components/users.jsx
src/plugin/cursus/Finder/EventPresenceFinder.php
src/plugin/cursus/Finder/Registration/CourseUserFinder.php
src/plugin/cursus/Finder/Registration/EventUserFinder.php
src/plugin/cursus/Finder/Registration/SessionUserFinder.php
src/plugin/cursus/Resources/modules/event/components/participants.jsx
src/plugin/cursus/Resources/modules/session/components/users.jsx
src/plugin/drop-zone/Finder/DropFinder.php
src/plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/correctors.jsx
src/plugin/drop-zone/Resources/modules/resources/dropzone/correction/components/drops.jsx
src/plugin/exo/Finder/PaperFinder.php
src/plugin/exo/Resources/modules/resources/quiz/papers/components/papers.jsx
src/plugin/open-badge/Finder/AssertionFinder.php
src/plugin/open-badge/Resources/modules/tools/badges/badge/components/details.jsx
src/plugin/scorm/Finder/ScoTrackingFinder.php
src/plugin/scorm/Resources/modules/resources/scorm/player/components/results.jsx

The following lists have been updated : 
- Resource evaluations (also added to the data source)
- Workspace evaluations (also added to the data source)
- Scorm results
- Quiz results (also added default filter to active)
- Dropzone results (also added default filter to active)
- Workspace users
- Training/Session/Event/Presence users (also added default filter to active)
- Badge users (also added default filter to active)

allows to filter on disabled users

---

src/main/core/API/Validator/UserValidator.php
src/main/core/Manager/FacetManager.php
src/main/core/Resources/config/services/validator.yml

| Fixed issues | #1963
Replaces https://github.com/claroline/Claroline/pull/1967

fixes #1963

---

src/main/app/ClarolineAppBundle.php
src/main/app/Resources/config/suggested/doctrine_prod.yml
src/main/app/Resources/config/suggested/doctrine_test.yml
src/main/app/Resources/config/suggested/messenger_prod.yml
src/main/core/DependencyInjection/Compiler/MessengerConfigPass.php
src/main/core/Installation/Migrations/pdo_mysql/Version20220316181246.php

The suggested configuration for messenger was not loaded.
Additionally, using a parameter to change the dsn of our transport does not work because of how messenger is configured in the framework so we need to modify the transport service definition directly.
Since the transport can be made sync as well as async, I renamed it from `async` to `default`.

Fix messenger configuration

---

package.json

Try to fix ` The unauthenticated git protocol on port 9418 is no longer supported.` error.

fixes js dependency

---

src/main/app/Resources/config/suggested/monolog_dev.yml
src/main/app/Resources/config/suggested/monolog_prod.yml

The new log file is named `messenger.log`.
NB. I've excluded the `messenger` channel from the main stream, but I'm not sure this was required (I did not find any messenger log in the main files).

[Messenger] stores logs in a specific file

---

src/main/community/Subscriber/Crud/RoleSubscriber.php
src/main/community/Subscriber/Crud/UserSubscriber.php

NB. It is not needed to check if the role is read only in a crud event, this has already be done by the voter.

[Community] deletes user role on user delete

---

src/main/core/Library/Normalizer/DateNormalizer.php

`DateTime::createFromFormat(static::DATE_FORMAT, $dateString)` returns `false` on failure and the `denormalize` method is expected to return `?\DatetimeInterface`

fixes DateNormalizer::denormalize return type

---

src/main/core/Resources/modules/resource/components/form.jsx

That's how the API works : we don't update the workspace score if the resource is not required.

[Resource] links evaluated flag to the required one in form

---

src/main/core/Resources/modules/resource/utils.js
src/main/core/Resources/modules/tool/components/page.jsx

Initially the rights button was put outside the dropdown because it was displaying a simplified version of the rights through the icon. This behavior has been removed, so there is no need to separate it from the Configure action.

[UI] hides configure rights button in more dropdown

---

src/main/core/Command/UpdateRichTextCommand.php

Basic version. The correct version is to use events.

fixes RichTextCommand when some plugins are disabled

---

src/main/app/Manager/File/TempFileManager.php
src/main/app/Resources/config/services/manager.yml
src/main/core/Configuration/LegacyParametersMapping.php
src/main/core/Configuration/PlatformDefaults.php
src/main/core/Library/GeoIp/Database/MaxMindGeoIpDatabaseDownloader.php
src/main/core/Resources/config/parameters.yml
src/main/core/Resources/config/services/library.yml
src/plugin/claco-form/Manager/ExportManager.php
src/plugin/claco-form/Resources/config/services/manager.yml
src/plugin/drop-zone/Manager/DropzoneManager.php
src/plugin/drop-zone/Resources/config/services/manager.yml

Tmp dir is now declared as a symfony parameter. This shouldn't be stored in `platform_options`.
We now use `/var/tmp` to store tmp files instead of the system one (default was set to `sys_get_temp_dir()`). This can create some security issued and also require to read/write inside a big folder.

uses local tmp dir

---

src/main/transfer/Transfer/Importer/AbstractImporter.php

If import lines are related to the same entity, there are special cases where the system will try to insert multiple times the same entities (ex. generate resource evaluations).

[Transfer] flushes each import line

---

src/main/core/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/main/theme/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/plugin/home/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/plugin/lesson/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/plugin/open-badge/Installation/Migrations/pdo_mysql/Version20230426080000.php
src/plugin/path/Installation/Migrations/pdo_mysql/Version20230426080000.php

I need it for the [symfony upgrade PR](https://github.com/claroline/Claroline/pull/2445).
There are old `json_array` columns in some of those tables and it makes doctrine crash when running the diff command.

drops obsolete tables from DB

---

composer.json
src/main/installation/Resources/config/bundles.ini-dist
src/main/privacy/ClarolinePrivacyBundle.php
src/main/privacy/Controller/PrivacyController.php
src/main/privacy/DependencyInjection/ClarolinePrivacyExtension.php
src/main/privacy/Resources/config/config.yml
src/main/privacy/Resources/config/routing.yml
src/main/privacy/Resources/config/services.yml
src/main/privacy/Resources/config/services/controller.yml
src/main/privacy/Resources/config/services/serializer.yml
src/main/privacy/Resources/config/services/subscriber.yml
src/main/privacy/Resources/modules/administration/privacy/components/tool.jsx
src/main/privacy/Resources/modules/administration/privacy/containers/tool.jsx
src/main/privacy/Resources/modules/administration/privacy/index.js
src/main/privacy/Resources/modules/administration/privacy/store/index.js
src/main/privacy/Resources/modules/administration/privacy/store/reducer.js
src/main/privacy/Resources/modules/administration/privacy/store/selectors.js
src/main/privacy/Resources/modules/plugin.js
src/main/privacy/Resources/translations/tools.en.json
src/main/privacy/Resources/translations/tools.fr.json
src/main/privacy/Subscriber/Administration/PrivacySubscriber.php

adds privacy plugin

---

docs/sections/application/plugins.md

Added in the doc section application/plugins.md the missing instruction concerning the bundles.ini file: 
``files/config/bundles.ini``  -> ``Claroline\YourPluginBundle\ClarolineYourPlugingBundle=true``

[Documentation] adds plugin in .ini

---

src/main/installation/Resources/config/bundles.ini-dist

A cause de l'échappement, le plugin n'était pas reconnu pas le kernel lors de l'activation automatique via le `bundle.ini-dist`
ping @WolfyWin FYI.

[YouTube] fixes plugin auto activation
